### ISSUE TITLE
docker-compose install not working with fresh db

### ISSUE THREAD

**Issue by msmicker** [ckan/ckan#3933] opened 2017-11-21 22:03 UTC
### CKAN Version if known (or site URL)
Master branch

### Please describe the expected behaviour
Starting fresh docker-compose build/up with new DB

### Please describe the actual behaviour
Seeing several errors in db logs (docker-compose logs db) after docker-compose up. Tried from 2 docker hosts starting fresh.

### What steps can be taken to reproduce the issue? 
From clean docker, (no images, containers, volumes) do docker-compose build and up

**Comment by gerbyzation** [comment] 2017-11-22 11:09
@msmicker could you add the errors you're seeing in the logs?

**Comment by SergK** [comment] 2017-11-23 14:34
Hi, it seems the below is the issue

```bash
Distribution already installed:
  ckan 2.8.0a0 from /usr/lib/ckan/venv/src/ckan
Creating /etc/ckan/ckan.ini
Now you should edit the config files
  /etc/ckan/ckan.ini
Traceback (most recent call last):
  File "/usr/local/bin/ckan-paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 356, in command
    model.repo.init_db()
  File "/usr/lib/ckan/venv/src/ckan/ckan/model/__init__.py", line 187, in init_db
    self.upgrade_db()
  File "/usr/lib/ckan/venv/src/ckan/ckan/model/__init__.py", line 284, in upgrade_db
    mig.upgrade(self.metadata.bind, self.migrate_repository, version=version)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<decorator-gen-16>", line 2, in _migrate
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 160, in with_engine
    return f(*a, **kw)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 366, in _migrate
    schema.runchange(ver, change, changeset.step)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/schema.py", line 93, in runchange
    change.run(self.engine, step)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/script/py.py", line 148, in run
    script_func(engine)
  File "/usr/lib/ckan/venv/src/ckan/ckan/migration/versions/001_add_existing_tables.py", line 105, in upgrade
    meta.create_all()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3934, in create_all
    tables=tables)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1929, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1538, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
    _is_metadata_operation=True)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 767, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
    compiled
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "id" referenced in foreign key constraint does not exist
 [SQL: '\nCREATE TABLE package (\n\tid SERIAL NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\ttitle TEXT, \n\tversion VARCHAR(100), \n\turl TEXT, \n\tdownload_url TEXT, \n\tnotes TEXT, \n\tlicense_id INTEGER, \n\tstate_id INTEGER, \n\trevision_id INTEGER, \n\tPRIMARY KEY (id), \n\tUNIQUE (name), \n\tFOREIGN KEY(license_id) REFERENCES license (id), \n\tFOREIGN KEY(state_id) REFERENCES state (id), \n\tFOREIGN KEY(revision_id) REFERENCES revision (id)\n)\n\n']

```

**Comment by mattfullerton** [comment] 2017-11-23 14:48
Do you have postgis (and in particular, tiger) installed in the DB?

**Comment by gerbyzation** [comment] 2017-11-23 16:08
seems to be the same issue as https://github.com/ckan/ckan/issues/3929

**Comment by SergK** [comment] 2017-11-23 16:19
@mattfullerton didn't dive deep yet, but the issue with running `docker-compose` from scratch so I believe we need to check this image
>FROM mdillon/postgis

**Comment by SergK** [comment] 2017-11-23 16:22
Why we didn't catch the issue before, because we are using cached docker containers, which IMO is wrong, so potentially we run our tests with slightly outdated images

**Comment by mattfullerton** [comment] 2017-11-23 16:22
See #3929

**Comment by msmicker** [comment] 2017-11-23 17:59
Thanks very much - that resolved it. Adding schema="public" as parameter to line 8 of 001_add_existing_tables.py

I confirmed I can build from scratch - it did require the restart of ckan, but as mentioned above that is already part of the docs.

**Comment by SergK** [comment] 2017-11-26 22:56
I propose to close this bug, since  this PR https://github.com/ckan/ckan/pull/3940 fixes it

**Comment by gerbyzation** [comment] 2017-11-27 17:11
@SergK When running master or my PR branch I'm still seeing this error? Also this issue seems to be a duplicate of #3929 so would second closing this one and moving further discussion over there

**Comment by SergK** [comment] 2017-11-27 17:47
@gerbyzation, yes my bad, I didn't clean db volume after running with `(schema='public')`

**Comment by ad-m** [comment] 2017-12-19 18:21
I today checkout master branch, remove all volumes, then up ``ckan`` container. Then I receive still folllowing exception:
```
$ git rev-parse HEAD
4016bacb3d311478211428f3c71be2582627f273
$ docker-compose up ckan
Starting redis ... 
Starting redis
Starting solr ... 
Starting db ... 
Starting solr
Starting redis ... done
Starting ckan ... 
Starting ckan ... done
Attaching to ckan
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 11, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan          |     invoke(command, command_name, options, args[1:])
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan          |     exit_code = runner.run(args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan          |     result = self.command()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 356, in command
ckan          |     model.repo.init_db()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/model/__init__.py", line 187, in init_db
ckan          |     self.upgrade_db()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/model/__init__.py", line 284, in upgrade_db
ckan          |     mig.upgrade(self.metadata.bind, self.migrate_repository, version=version)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
ckan          |     return _migrate(url, repository, version, upgrade=True, err=err, **opts)
ckan          |   File "<decorator-gen-16>", line 2, in _migrate
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 160, in with_engine
ckan          |     return f(*a, **kw)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 366, in _migrate
ckan          |     schema.runchange(ver, change, changeset.step)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/schema.py", line 93, in runchange
ckan          |     change.run(self.engine, step)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/migrate/versioning/script/py.py", line 148, in run
ckan          |     script_func(engine)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/migration/versions/001_add_existing_tables.py", line 105, in upgrade
ckan          |     meta.create_all()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3934, in create_all
ckan          |     tables=tables)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1929, in _run_visitor
ckan          |     conn._run_visitor(visitorcallable, element, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1538, in _run_visitor
ckan          |     **kwargs).traverse_single(element)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
ckan          |     return meth(obj, **kw)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
ckan          |     _is_metadata_operation=True)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
ckan          |     return meth(obj, **kw)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 767, in visit_table
ckan          |     include_foreign_key_constraints=include_foreign_key_constraints
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
ckan          |     return meth(self, multiparams, params)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
ckan          |     return connection._execute_ddl(self, multiparams, params)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
ckan          |     compiled
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
ckan          |     context)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
ckan          |     exc_info
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
ckan          |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
ckan          |     context)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
ckan          |     cursor.execute(statement, parameters)
ckan          | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "id" referenced in foreign key constraint does not exist
ckan          |  [SQL: '\nCREATE TABLE package (\n\tid SERIAL NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\ttitle TEXT, \n\tversion VARCHAR(100), \n\turl TEXT, \n\tdownload_url TEXT, \n\tnotes TEXT, \n\tlicense_id INTEGER, \n\tstate_id INTEGER, \n\trevision_id INTEGER, \n\tPRIMARY KEY (id), \n\tUNIQUE (name), \n\tFOREIGN KEY(license_id) REFERENCES license (id), \n\tFOREIGN KEY(state_id) REFERENCES state (id), \n\tFOREIGN KEY(revision_id) REFERENCES revision (id)\n)\n\n']
ckan exited with code 1
```

I bought VPS C2S (x86) from Scaleway. On fresh Ubuntu 16.04 I got following logs (build on fresh docker installation): http://wklej.org/hash/7ec169023fc/txt/

**Comment by gerbyzation** [comment] 2017-12-20 19:11
@ad-m this is a duplicate thread, if you look at the other issue https://github.com/ckan/ckan/issues/3929 you'll see a fix is being worked on

**Comment by kmbn** [comment] 2019-01-23 14:59
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.

**Closed by kmbn** 2019-01-23 14:59 UTC
