### ISSUE TITLE
CKAN resource tables not updated

### ISSUE THREAD

**Issue by sheeba123** [ckan/ckan#4463] opened 2018-09-16 07:48 UTC
### CKAN Version if known (or site URL)
2.8
### Please describe the expected behavior
Production site links pointing to dev env resources

### Please describe the actual behavior
CKAN app cloned from development env to production .All resource url are pointing to dev server.
I want to update resource table so that it will point to actual resource in production
Please suggest

### What steps can be taken to reproduce the issue? 
Update url field of the resource and resource_revision tables on the database with SQL query 
Rebuild index using : paster --plugin=ckan search-index rebuild --config=/etc/ckan/default/production.ini
This output I am getting after rebuilding index
2018-09-16 09:16:48,009 INFO [ckan.lib.search] Rebuilding search index...
2018-09-16 09:16:48,012 INFO [ckan.lib.search] Rebuilding the whole index...
Indexing dataset 82/822018-09-16 09:16:49,792 INFO [ckan.lib.search] Finished rebuilding search index.
2018-09-16 09:16:49,857 INFO [ckan.lib.search] Commited pending changes on the search index

UI not updated with new values

**Comment by wardi** [comment] 2018-09-18 12:07
What's the SQL query you're using to update the resource URLs?

**Comment by wardi** [comment] 2018-09-19 15:16
closing as a duplicate of #4198 also work on #4384 should fix the underlying issue

**Closed by wardi** 2018-09-19 15:16 UTC

**Comment by rp-21** [comment] 2018-12-19 07:57
in this case rebuilding the index alone wouldn't help. First need to run a custom sql query in the db sql prompt to replace the domain name with the desired pattern and then rebuilding the index. 

I doubt even in such case it would work since you need to make sure that the datastore extension and files are in your prod db.

The Best approach to this is to write a script that would access your dev environment db,files and post them into your prod environment using ckanapi.
