### ISSUE TITLE
Can't build docker CKAN instance (/example_theme_most_popular_groups.html)

### ISSUE THREAD

**Issue by RaulBS09** [ckan/ckan#4710] opened 2019-03-28 16:23 UTC
### CKAN Version
2.8.2

### What steps can be taken to reproduce the issue? 
Clone CKAN and checkout a stable version.
```
git clone https://github.com/ckan/ckan.git
cd ckan
git checkout tags/ckan-2.8.2
```

Sensitive settings and environment variables and building images.
```
cp contrib/docker/.env.template contrib/docker/.env

cd contrib/docker
docker-compose up -d --build
```

### ERROR:
ERROR: Error processing tar file(exit status 1): open /ckanext/example_theme_docs/custom_config_setting/templates/snippets/example_theme_most_popular_groups.html: no such file or directory

Because of this error I can't even start a valid CKAN instance for testing the tool.

**Comment by davidread** [comment] 2019-04-03 22:12
@RaulBS09 I don't get that error. I get this on my mac instead: https://gist.github.com/davidread/2d8c737489afbc5ab2f60b0e8afaddaf

That "tar file" error makes me think you're not doing this on *nix, and therefore not a bug with CKAN, so closing this issue. Feel free to ask for help from the wider CKAN community on stackoverflow etc

**Closed by davidread** 2019-04-03 22:12 UTC
