### ISSUE TITLE
Updating organisation does not update organisation in its packages

### ISSUE THREAD

**Issue by trickvi** [ckan/ckan#2659] opened 2015-09-30 12:17 UTC
Updating a title of an organisation via the API call does not update it's packages, it become apparent in the response which includes both old and new version of organisation, e.g. updating an organisation called "Another organization" to have the name "A different organization":

    http --json POST http://127.0.0.1:5000/api/3/action/organization_update id=another-organization title="A different organization" Authorization:api-key

Gives this response (I remove cruft):

```json
{
    "help": "http://localhost:5000/api/3/action/help_show?name=organization_update", 
    "result": {
        "description": "Description for this other organisation", 
        "display_name": "A different organization", 
        "name": "another-organization", 
        "package_count": 1, 
        "packages": [
            {
                "name": "a-dataset", 
                "notes": "A dataset description", 
                "organization": {
                    "description": "Description for this other organisation", 
                    "name": "another-organization", 
                    "title": "Another organization", 
                }, 
                "owner_org": "a3c4b4b8-961d-45f4-8981-728653f36445", 
            }
        ], 
        "title": "A different organization", 
        "type": "organization", 
    }, 
    "success": true
}
```

Note the organization dictionary in the packages dictionary (the redundant one). It's not updated. And if I run a package_show I also get the old title of the organization (again I remove cruft):

    http --json http://127.0.0.1:5000/api/3/action/package_show id=4e77badd-cd28-4825-97f1-9e2dffdbb002 Authorization:api-key

```json
{
    "help": "http://localhost:5000/api/3/action/help_show?name=package_show", 
    "result": {
        "name": "a-dataset", 
        "notes": "A dataset description", 
        "organization": {
            "description": "Description for this other organisation", 
            "name": "another-organization", 
            "revision_id": "a6b9d4be-d7da-48d6-8c14-f170f03e899e", 
            "title": "Another organization", 
            "type": "organization"
        },
    "success": true
}
```

**Comment by amercader** [comment] 2015-10-02 12:15
This is an issue that has been know for a while. The problem is that the datasets dicts need to be reindexed in Solr in order for the new org details to be updated. For organizations with several datasets (hundreds) this takes too much time to do on the same request as the org update.

The ideal solution would be to have a generic queue available that we could send this type of jobs to. Some discussion on that front can be found here: https://github.com/ckan/ideas-and-roadmap/issues/66

**Comment by trickvi** [comment] 2015-10-02 14:46
Feel free to close if this is a duplicate.

**Comment by davidread** [comment] 2015-10-06 13:02
This is a duplicate of #1796, but thanks for raising. Remains needing a fix, using a queue.

**Closed by davidread** 2015-10-06 13:02 UTC
