### ISSUE TITLE
visualize statistics data into charts and graphs

### ISSUE THREAD

**Issue by Abdelrahman146** [ckan/ckan#5180] opened 2020-01-29 13:08 UTC
How can I configure the stats extension to visualize the data into graphs and charts similar to this example:

![visualized stats extension](https://i.gyazo.com/036101a957ea95c2209c1557e453092d.png)

![visualized stats extension](https://i.gyazo.com/e9753450cdf60722bbdc3dfe6d37e3d1.png)

**Comment by smotornyuk** [comment] 2020-02-03 07:38
You need to add `data-module="plot"` to tables with statistics should be visualized and(important) make sure, that section with the graph is visible while page is loading(it's current requirement of javascript used for visualisation).

Or, you can use such js on stats page:
```javascript
$('a[data-toggle=tab]').on(
  'click', 
  (e) =>
    setTimeout((table => table &&
    ckan.module.initializeElement(
      table
    )), 100, $(e.target.getAttribute('href')).find('[data-module=plot]')[0])
)
```
but, it's only a quick hack(as you can see by timeout), so i storngly recommend not to insert this particular snippet, but rather use it as starting point and adapt/improve it for your needs.

**Comment by clauded** [comment] 2020-02-03 20:53
I'm facing the same issue but I don't understand what needs to be changed.

By default, stats tables already have the **data-module="plot"** attribute. 

What do you mean by "make sure, that section with the graph is visible while page is loading"?

**Comment by smotornyuk** [comment] 2020-02-04 05:44
There are few tabs on this page, and only active one shows its content. If table, that is going to be converted into graph is placed under inactive tab, it's not visible and won't be converted - there are a number of issues with sizes and usually(like in our case) invisible content shouldn't be initialized, unless it is shown to user(that's what suggested JS code does - when tab is activated, it waits a bit, while transition is finished, and then initializes the graph)
So, theoretically, if the tab with the table is active during page-load, it should be converted into a graph. Though there may be an issue with JS that controls tabs - when the page is loaded, it strips out content for an instant in order to put it into relevant tabs - and in this particular moment `data-module="plot"` is activated - this may be the reason, why `data-module` is ignored.

This page requires some attention and a bit of redevelopment, but as everyone in core team is busy with v2.9 preparations, it's unlikely, that there will be some progress here in a month or two.

**Comment by clauded** [comment] 2020-02-04 16:09
Thanks for the info.

I tried your script but I get this error: **stats:174 Uncaught ReferenceError: $ is not defined**

**Comment by smotornyuk** [comment] 2020-02-04 16:13
try to replace `$` by `jQuery` if you are using dev console of your browser. If you are attaching this script  to page, make sure jQuery loads before script gets executed

**Comment by clauded** [comment] 2020-02-04 16:54
Thanks. jQuery is loaded at the bottom of CKAN pages so here's my ugly code to make this work partially (it will only show graph when clicking on the corresponding tab so it's far from finished):

```
<script type="text/javascript" src="/fanstatic/vendor/:version:2020-01-06T10:54:26.11/jquery.min.js"></script>
<script>
$('a[data-toggle=tab]').on(
  'click',
  (e) =>
    setTimeout((table => table &&
    ckan.module.initializeElement(
      table
    )), 100, $(e.target.getAttribute('href')).find('[data-module=plot]')[0])
) 
</script>
```
For sure, there must be a simpler way to accomplish this. Also I noted they removed the data-module="plot" attribute in the[ 2.9 code](https://github.com/ckan/ckan/blob/master/ckanext/stats/templates/ckanext/stats/index.html). So I wonder if it will be supported in the future.

**Comment by Chealer** [comment] 2020-05-07 18:53
Can you clarify why this ticket was closed @smotornyuk ?

**Comment by smotornyuk** [comment] 2020-05-07 23:34
Because this ticket was started from a question, that was answered. Usually, we are suggesting to ask such questions on StackOverflow, and use issues in the repository for bug-reporting

Those charts are not an "active" feature - it's just legacy functionality. The whole statistics section was not receiving any attention for a long time, there were no new features and no one was interested in maintaining it. Some organizations even extracted statistics into separate extension - https://github.com/datagovau/ckanext-dga-stats for example. In the master branch stats are broken for a while(we are not using VDM library anymore, but stats are relying on it), there is a PR under review (#5215) that removes a bunch of code-lines for restoring minimal working state. If no one will be interested in it after v2.9 release, I'm going to do some work in order to restore all previously existing features and add some new interactive widgets.

**Closed** 2020-05-07 23:34 UTC

**Comment by Chealer** [comment] 2020-05-08 14:56
Thanks @smotornyuk , I agree this looked more like a support request.

It turns out this request was caused by a bug. I filed ticket #5375 to report it.
