### ISSUE TITLE
I should be able to see my own private datasets on the search page

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#2768] opened 2015-12-03 11:38 UTC
I'm not sure if there was some technical reason not to show them, but it was a bit surprising.

**Comment by amercader** [comment] 2015-12-03 16:59
Duplicate of https://github.com/ckan/ckan/issues/1239

Essentially the Solr query is complicated. We need a filter that says "return all public datasets and all private datasets from org X, Y and Z" (the orgs a user is member of).

It sounds definitely doable, not sure how it would affect performance on large instances, but if someone is willing to try go for it!

**Comment by fibonaki** [comment] 2016-02-12 09:38
I felt disappointed once I realised about that. After considering Ckan as a great solution for our purpose  and for our information catalog needs, we cannot use searcher to find private data. It seems that can not be possible. Is there any feasible action to do to "activate" this kind of searches?

**Comment by gleb-rudenko** [comment] 2017-02-22 13:03
@amercader , I'll work on it

**Comment by wardi** [comment] 2017-02-22 13:07
This was fixed in 2.6 by #3191

**Closed by wardi** 2017-02-22 13:07 UTC
Labels: Good for Contribution
