### ISSUE TITLE
DataPusher raises exception when updating resource

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#5597] opened 2020-09-11 01:07 UTC
**CKAN version**: 2.9 (commit f2c92c3ab5)
**DataPusher version**: 45be714c

**Describe the bug**

Everything runs fine when I create a new dataset resource. However, when I try to update the data on that resource, I get an Internal server error. The logs say:

```
2020-09-10 22:01:05,018 DEBUG [ckanext.datapusher.plugin] Submitting resource a1b7fa8e-6d34-49b2-9771-ac5651e6c5a7 to DataPusher
2020-09-10 22:01:05,062 DEBUG [ckanext.datapusher.plugin] Skipping DataPusher submission for resource a1b7fa8e-6d34-49b2-9771-ac5651e6c5a7
2020-09-10 22:01:05,228 ERROR [ckan.config.middleware.flask_app] 'NoneType' object has no attribute 'transaction'
Traceback (most recent call last):
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/ckan-2.10.0a0-py3.7.egg/ckan/config/middleware/../../views/resource.py", line 367, in post
    get_action(u'resource_update')(context, data)
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/ckan-2.10.0a0-py3.7.egg/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/ckan-2.10.0a0-py3.7.egg/ckan/logic/action/update.py", line 104, in resource_update
    updated_pkg_dict = _get_action('package_update')(context, pkg_dict)
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/ckan-2.10.0a0-py3.7.egg/ckan/logic/__init__.py", line 473, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/ckan-2.10.0a0-py3.7.egg/ckan/logic/action/update.py", line 344, in package_update
    model.repo.commit()
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/vitor/Projetos/okfn/ckan/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 474, in _prepare_impl
    stx = self.session.transaction
AttributeError: 'NoneType' object has no attribute 'transaction'
```

**Steps to reproduce**

1. Create a new dataset
2. Add a CSV resource to the dataset
3. Modify the resource, removing and submitting the same CSV

**Expected behavior**

The resource will be updated, with the new data being submitted to the DataStore.

**Additional details**

This is the same error described in https://github.com/ckan/ckan/pull/5173, #5137, and #4751. However, while these issues talk about creating a new resource, this error only happens when updating a resource.

**Comment by elrokket** [comment] 2020-10-09 12:07
I have the same error, when update dataset with associated resources return this error 2020-10-09 11:27:30,649 ERROR [ckan.views.api] 'NoneType' object has no attribute 'transaction'

any news about this issue? thanks

**Comment by jodiegardiner** [comment] 2020-10-14 08:24
can confirm we're having the same issue  with resource_update via API

**Comment by rohillion** [comment] 2020-10-16 08:55
Any clues of when this will be fixed?

**Comment by jonathansberry** [comment] 2020-10-30 12:00
@amercader I've spent a while looking in to it... It's basically as you've already laid out in the PR: https://github.com/ckan/ckan/pull/5173

- the notify method of the datapusher plugin calling...
- the _submit_to_datapusher method of the datapusher plugin calling...
- the datapusher_submit action calling the...
- update_task_status action which...
- gets the main session, makes some changes, commits then closes the session

I was surprised that we we were closing the session here. However, removing the close statement didn't fix the issue.  So I tried using a new session with meta.create_local_session() instead of the main session and that appeared to fix the issue.  I then started going back through the git history and found this commit showing that in CKAN 2.8 when this feature was stable, we did indeed create a new session back then: 

https://github.com/ckan/ckan/commit/ca4464ab1de2a8cb51a4f9254725d6f8da0b80b9

Maybe @smotornyuk could comment on the intent of the above commit and how it checks out against this issue?  I don't understand all the design decisions here, so maybe this commit is doing something important that I have missed. I considered opening a PR, but it seems a bit silly for a one liner. 

For anyone else (@rohillion, @jodiegardiner, @elrokket) as a stop-gap measure whilst we wait for a solution in a stable core ckan release, we have overridden the 'task_status_update' action from one of our extensions, and implemented this fix there:
https://github.com/fjelltopp/ckanext-unaids/commit/5b5d719b9d311ac02b8da511857ca9198cb4a6d5

**Comment by abedkhooli** [comment] 2020-11-02 17:28
> 
> 
> Any clues of when this will be fixed? We are getting a 500 error after uploading a new CSV to an existing resource.

Also confirming same in 2.9.1

**Comment by smotornyuk** [comment] 2020-11-06 19:00
Yes, I replaced the call to `create_local_session` because it was the single usage of the local session through the whole codebase, and there was no real distinction of this action from any other, so this line looked really nasty. Even now it looks like an attempt to fix the consequences of a problem, instead of solving its origin, so it would be great to search for alternative solutions(not using local session). BTW, I removed the local session there, because some tests were failing on py3 because of it, so it's more than "just getting this line back" in any case

**Comment by jonathansberry** [comment] 2020-11-10 07:54
@smotornyuk That's great.  Thanks for the explanation - also great to know that there are py3 tests failing because of it. We'll just hold onto this as a stop gap fix then until a better solution is devised by the team.

**Comment by jqnatividad** [comment] 2020-12-06 19:58
Also confirming that I'm getting this error as well...

**Comment by jqnatividad** [comment] 2020-12-07 21:22
@smotornyuk digging into this a bit, there was a specific reason why `create_local_session` was explicitly created by @johnglover for `task_status_update` back in Dec 2011.  

Per the commit msg:
> Use a local session object in task_status_update so we can commit it at the end of the function

https://github.com/ckan/ckan/commit/520959ca6f83586d33cf7d4015d625a776ee46a1#diff-0d9877c849b4b462a8bdc9337551a3e63ddb1189513bd0e13ed59fc502d9d42c

CKAN was using [sqlalchemy 0.7.3](https://docs.sqlalchemy.org/en/14/changelog/changelog_07.html#change-0.7.3) at [the time](https://github.com/ckan/ckan/blob/520959ca6f83586d33cf7d4015d625a776ee46a1/requires/lucid_conflict.txt), and sqlalchemy has seen a lot of changes since then in terms of handling sessions... 

Perhaps, its not necessarily a "nasty" but necessary thing to "commit it at the end of the function" at the time, and there's now a more elegant way of doing it as the CKAN codebase is being modernized?

cc @jonathansberry @abedkhooli @rohillion @jodiegardiner @elrokket @vitorbaptista

**Comment by jqnatividad** [comment] 2021-01-19 13:26
@smotornyuk , just wondering if the root cause for using local session has been found, and if not, if it will be reverted back to using a local session in the meantime, so it can be part of 2.9.2...

**Comment by cfotnz** [comment] 2021-04-16 15:41
Hey, I'm using 2.9.2 and facing the exact same issue. Is it going to be fixed in the next release?

**Comment by jqnatividad** [comment] 2021-05-04 12:30
Any ETA on a fix for this? I can confirm that the workaround (using LocalSession) works. Has the team considered reverting back in the meantime?

**Comment by smotornyuk** [comment] 2021-06-07 12:24
Opened PR#6137 with a fix

**Closed** 2021-06-09 13:00 UTC
