### ISSUE TITLE
UnicodeEncodeError error when trying to add or edit a resource view

### ISSUE THREAD

**Issue by georgepm** [ckan/ckan#2347] opened 2015-03-15 14:51 UTC
For some files on ckan 2.3, the recline_view preview works correctly, but trying to add or edit a new view for them, shows Server Error.

The ckan error log shows:

```
File '/ckan/lib/default/src/ckan/ckan/lib/helpers.py', line 1806 in remove_linebreaks
return str(string).replace('\\n', '')
UnicodeEncodeError: 'ascii' codec can't encode character u'\\ufeff' in position 661: ordinal not in range(128)
```

Maybe the ckan/lib/helpers.py [1806](https://github.com/ckan/ckan/blob/ckan-2.3/ckan/lib/helpers.py#L1806) line, should be changed to:

```
    return unicode(string).replace('\n', '')
```

**Comment by u10313335** [comment] 2015-04-04 09:25
Had the same issue and it can be fixed using @georgepm's method.

**Comment by manuelpalacin** [comment] 2015-05-12 10:27
Dear all,
I found the same error but with other views. For example I am trying to introduce a dataset in Chinese (csv or excel), but when I am trying to create a Pie Chart it throws a 500 Server Error. If you look at the log it appears:

[Tue May 12 09:59:19.077884 2015] [:error] [pid 34582:tid 140431636506368] [remote 127.0.0.1:37058] File '/usr/lib/ckan/default/src/ckanext-viewhelpers/ckanext/viewhelpers/plugin.py', line 18 in _remove_linebreaks
[Tue May 12 09:59:19.077888 2015] [:error] [pid 34582:tid 140431636506368] [remote 127.0.0.1:37058]   return str(string).replace('\\n', '')
[Tue May 12 09:59:19.077893 2015] [:error] [pid 34582:tid 140431636506368] [remote 127.0.0.1:37058] UnicodeEncodeError: 'ascii' codec can't encode characters in position 131-132: ordinal not in range(128)

But using the @georgepm solution it works:
line 18 '/usr/lib/ckan/default/src/ckanext-viewhelpers/ckanext/viewhelpers/plugin.py'
You should change:
return str(string).replace('\\n', '') 
for: 
return unicode(string).replace('\n', '')

**Comment by amercader** [comment] 2015-06-15 20:59
Dupe of #2420

**Closed by amercader** 2015-06-15 20:59 UTC
Labels: Backport 2.3.1, Backport pending, Resource Views
