### ISSUE TITLE
"My Organizations" only show the organizations that I'm an admin of

### ISSUE THREAD

**Issue by filipefigcorreia** [ckan/ckan#2594] opened 2015-08-24 16:10 UTC
I'm finding that the "My Organizations" tab on the user dashboard doesn't display all the organizations that the user belongs to (in fact, on my CKAN instance it's often empty, and just displays the text "You are not a member of any organizations"). 

Apparently, the organizations on which the user has the role of "editor" or "member" don't appear, and only those on which the user is an "admin" get listed on this tab.

In case this is a bug, I guess the solution may be to pass a different permission (``'read'``?) to the ``organizations_available()`` method on the [dashboard_organizations.html](https://github.com/ckan/ckan/blob/master/ckan/templates/user/dashboard_organizations.html#L13) template.

**Comment by amercader** [comment] 2015-08-25 14:49
@filipefigcorreia this is a duplicate of https://github.com/ckan/ckan/pull/2457 I'll check what is its status

@brew you were right, this had come up before, I guess I'm losing memory as it was a PR of mine :)

**Closed by amercader** 2015-08-25 14:49 UTC

**Comment by filipefigcorreia** [comment] 2015-08-25 15:02
@amercader Cool. Are there plans to merge it soon? :-) It'd come in handy!

**Comment by amercader** [comment] 2015-08-25 15:03
@filipefigcorreia It just needs some tests, I'll try to add them at some point this week
