### ISSUE TITLE
Password reset fails if user API is not public

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#6777] opened 2022-03-30 04:11 UTC
Requesting a password reset uses the `ignore_auth` flag to access a user profile. However, _performing_ the reset does not, causing a failure if `ckan.auth.public_user_details` is set to False. See https://github.com/ckan/ckan/blob/fc91b296da2e6d7d6cfbb949d6616fcabe072640/ckan/views/user.py#L720

This affects both CKAN 2.8 and 2.9.

Steps to reproduce:

- Configure a CKAN instance with `ckan.auth.public_user_details = False`
- Perform a password reset for any account.

**Comment by Zharktas** [comment] 2022-03-30 08:30
Isn't this the same old issue which we previously discussed in #5185 ? Are you still blocking anonymous access which also blocks checks for public user details ?

**Comment by TomeCirun** [comment] 2022-03-30 11:00
hey @ThrawnCA can you tell me more details because i cannot reproduce this error on `CKAN 2.9.5`. (I'm trying to reset user password via `UI`) 

Thanks

**Comment by ThrawnCA** [comment] 2022-03-30 12:23
@TomeCirun The key is to configure your CKAN instance so that access to the `user_show` API is restricted. Setting the `ckan.auth.public_user_details` flag to False should do it, although [our extension](https://github.com/qld-gov-au/ckan-ex-qgov) goes further and only allows access for group/organisation admins, or if you're accessing your own record.

When `ckan.views.user.PerformResetView._prepare` tries to load up the user_dict by calling `user_show`, it fails due to the restriction.

**Comment by Zharktas** [comment] 2022-03-30 13:43
@ThrawnCA it was never fixed as I feel that removing auth checks just hide the underlying issue that when you are removing anonymous access from `user_show`, the remaining auth checks for it are never run and it fails. There might be various other places where it would similarly fail and your usecase is not covered by tests and might not be even recommended. But I'll discuss it with the tech team tomorrow how they feel about it.

**Comment by TomeCirun** [comment] 2022-03-30 15:11
Hey, @ThrawnCA 

when i click on the reset link that im getting on my email... that link contains the ID of the user and when we try to access `user_show`, we are sending that user ID in it. 
Inside `user_show` we are trying to get the `user_obj` from that id (https://github.com/ckan/ckan/blob/96cb766218f723a398cd2a03059bd32b978701f1/ckan/logic/action/get.py#L1405-L1407) 
and as you can see we fill in the `context` with the `user_obj`, when we call `_check_access` at line 413 (https://github.com/ckan/ckan/blob/96cb766218f723a398cd2a03059bd32b978701f1/ckan/logic/action/get.py#L1413) inside `user_show`  we do call `restric_anon()` but with the context, and remember our context has the `user_obj` in it so it's gonna return `{'success': True}`  thats why i cannot reproduce this error.  
as i can see in your repo, `user_show` has a bit different code than mine,  inside your code at line 1432: (https://github.com/qld-gov-au/ckan/blob/50299d54dd370ab7ff4ed819e5f0b0023038f652/ckan/logic/action/get.py#L1436-L1437) you are repopulating the `data_dict['id']` with the `context.get('user')`... you should check what value has the `context['user']` as i suspect this is where the error is comming from. 

Thanks

**Comment by ThrawnCA** [comment] 2022-03-30 21:20
@TomeCirun We haven't modified `ckan/logic/action/get.py`. I think you're looking at master, while ours is based on 2.9.4 (and 2.9.5 appears to be unchanged).

If the latest master really can call `user_show` successfully even with `ckan.auth.public_user_details` set to False, does that mean that `ckan.auth.public_user_details` is actually ineffective? It can't actually restrict access?

**Comment by Zharktas** [comment] 2022-03-31 05:24
@ThrawnCA I did a quick test with master and it still responds with Forbidden if user is not logged in when `public_user_details`is false

**Comment by TomeCirun** [comment] 2022-03-31 07:54
@ThrawnCA it works as Jari said.

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/72216462/160992939-e10127dc-75b1-4442-99ee-9f274996400e.png">

What I m trying to say is that we are not `anonymous` after you click on the email link, it has our `user.id` and we are passing it to our `context['user']`: 
https://github.com/ckan/ckan/blob/96cb766218f723a398cd2a03059bd32b978701f1/ckan/views/user.py#L680-L688

what  our auth function is doing, is: checking at first if `ckan.auth.public_user_details` is set to `False`, then it checks if the user is anon:

https://github.com/ckan/ckan/blob/96cb766218f723a398cd2a03059bd32b978701f1/ckan/authz.py#L541-L551

`context['user']` is not empty it has our `user.ID` so it passes the authentication... 
you should check what comes to your `ID`  and track down to auth functions and see what's happening there...

ps. Can you tell me about exact way of doing it? I m trying via UI, and you have mentioned token on your PR? 

Thanks

**Comment by ThrawnCA** [comment] 2022-04-08 00:59
Ah, I think I understand the situation better now.

The reason for the failure is because our custom auth function was not annotated with `@auth_allow_anonymous_access` (and was not in a module named `get.py`, so the annotation value defaults to False). This is something we can fix on our end.

However, it also highlights the fact that although `PerformResetView._prepare` _does_ populate the context with the user ID, it _does not_ populate `auth_user_obj`, which is what `auth_allow_anonymous_access` affects.

It's a little counter-intuitive to have to annotate our function to allow anonymous access to make it work, when in fact we _don't_ allow anonymous access and don't want to. But we can work around it.

**Comment by Zharktas** [comment] 2022-04-08 04:59
We did have a discussion yesterday that it is somewhat counter-intuitive when all the function in `get.py` is annotated with `auth_allow_anonymous_access` automatically behind the scenes. We could change that and annotate all then functions as the developers will look at the code anyway when they are overriding the functions. 

For `user_show` the auth logic could be changed as it is now that first it allows anonymous user and the next auth function denies anonymous user based on the config option.

**Comment by ThrawnCA** [comment] 2022-04-08 05:52
@Zharktas Should populating the context with a user ID be sufficient to quality as "authenticated" for the purposes of the `auth_allow_anonymous access` check?

**Comment by Zharktas** [comment] 2022-04-11 05:57
@ThrawnCA the code is looking for `auth_user_obj` in context https://github.com/ckan/ckan/blob/b88286ecdf224732d7c86a9956b9038b629ad531/ckan/authz.py#L233-L234

**Comment by Zharktas** [comment] 2022-04-11 05:58
Closing this as duplicate of #5185

**Closed by Zharktas** 2022-04-11 05:58 UTC

**Comment by ThrawnCA** [comment] 2022-04-11 06:46
> @ThrawnCA the code is looking for `auth_user_obj` in context

I know. My question was, should it look for the `user` object (which password resets populate with an ID) and accept that as an alternative?
