### ISSUE TITLE
When new upload file name is same as old, datapusher doesn't fire

### ISSUE THREAD

**Issue by deniszgonjanin** [ckan/ckan#2459] opened 2015-06-05 19:15 UTC
I haven't dug into where the problem is exactly, but it goes like this:

1. Have datastore/datapusher enabled
2. Create a resource that will automatically be uploaded to datastore via datapusher
3. Upload a new file, with the same file name, into the same resource - replacing the old one.
4. Datapusher should push the new file into datastore, but it does not.

If file name in step 3 is different than the old file name, everything works as expected.

**Comment by mattfullerton** [comment] 2015-06-05 20:27
This might or might not be related to #2437

**Comment by deniszgonjanin** [comment] 2015-06-05 20:33
@mattfullerton quite possibly!

**Comment by amercader** [comment] 2015-06-09 11:14
Also maybe #2147 / #2148 ?

**Comment by wardi** [comment] 2015-07-03 20:38
closing as duplicate of #2147

**Closed by wardi** 2015-07-03 20:38 UTC
