### ISSUE TITLE
Random renaming of field/column header in data preview grid

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#2943] opened 2016-04-05 00:10 UTC
### CKAN Version if known (or site URL)
CKAN 2.4.1 (https://datastore.landcareresearch.co.nz/)
  
I replicated the problem on demo.ckan.org as well. 
  
### Expected behaviour
When you filter a data explorer grid view to show more or less rows of data, the column/field headings should stay the same.
  
### Actual behaviour
When viewing a particular resource, I attempted to filter how many rows were displayed, and one of the column headings changed to a comment to do with the graph layout (even though I was looking at the grid view, not graph).
  
It only seems to be on the Data Explorer grid view.  If you use a simple Grid View then the problem does not occur

### What steps can be taken to reproduce the issue? 
Open the resource https://datastore.landcareresearch.co.nz/dataset/waitutu-sortie-nz-2001-2008/resource/559d79d5-63ba-47c6-b621-5cbcb2de078f 

Notice that there is a column header 'P'.  Change the number of records to be diplayed to (say) 33. Now look what Column 'P' heading has changed too.

See attached pdf for screen shots.
[ckan column header issue.pdf](https://github.com/ckan/ckan/files/203550/ckan.column.header.issue.pdf)

**Comment by amercader** [comment] 2016-04-05 09:06
This is most likely caused by #2923. Closing this in favour of the previous issue 
cc @smotornyuk

**Closed** 2016-04-05 09:24 UTC
