### ISSUE TITLE
Organization page displays 0 datasets for all organizations, CKAN 2.4.X

### ISSUE THREAD

**Issue by pkoskinen** [ckan/ckan#2734] opened 2015-11-16 05:10 UTC
The package_count is always 0, no matter how many public datasets can be found in the organization. The feature can be seen in http://beta.ckan.org/organization as well.

**Comment by amercader** [comment] 2015-11-17 13:16
thanks @pkoskinen. This was fixed in #2557 and backported to 2.4.1.

beta.ckan.org was running 2.4.0 but it has now been updated and the issue is gone: 

http://beta.ckan.org/organization

**Closed by amercader** 2015-11-17 13:16 UTC
