### ISSUE TITLE
Extending sprite resource icons with JPG/JPEG icons

### ISSUE THREAD

**Issue by earthquakesan** [ckan/ckan#2910] opened 2016-03-13 15:28 UTC
### CKAN Version if known (or site URL)

2.5.0a
### Please describe the expected behaviour

Resources JPEG/JPG mimetype/format should have a specific icon on the dataset view (i.e. http://example.com/dataset/my-dataset) similar to XML/JSON/HTML icons from https://github.com/ckan/ckan/blob/master/ckan/public/base/images/sprite-resource-icons.png 
### Please describe the actual behaviour

Right now the icon is DATA (the first one on the sprite-resource-icons.png), which is the icon for generic resources.
### What steps can be taken to reproduce the issue?
- Install CKAN with datastore extension enabled
- Create example dataset
- Create a resource and upload JPG image to the resource

**Comment by amercader** [comment] 2016-03-15 13:20
@earthquakesan That sounds good, the problem is that the original Photoshop or GIMP file is not in the repo. Perhaps @aron still has it somewhere lying around. 
If any new formats can be added to the sprite somehow then it's just a matter of editing the relevant bits of the less file: https://github.com/ckan/ckan/blob/91e41b2e68faa3df5296a632f4862f5a55e69e62/ckan/public/base/less/dataset.less

**Comment by aron** [comment] 2016-03-16 19:46
@amercader just checked through my computer but couldn't find any design assets. I have a feeling we kept them on Google Drive or something similar...

**Comment by earthquakesan** [comment] 2016-03-22 11:36
@aron @amercader would it be possible to find and share them?

**Comment by seebi** [comment] 2016-04-04 08:14
@amercader What about the source of this? Did you find it?

**Comment by amercader** [comment] 2016-04-04 09:02
@seebi @earthquakesan Found them! @smth keeps a repo with them over here: https://github.com/mintcanary/file-types

**Comment by hknochi** [comment] 2016-04-11 11:59
this problem will be fixed by pull-request #2948

**Comment by AnjaStemme** [comment] 2018-01-17 09:04
Hi,

would it be possible to have more icons? For example as well for .doc .odt and separate image icons for png jpg gif?

**Comment by smth** [comment] 2018-02-18 21:04
I just added a the types suggested here (over at https://github.com/mintcanary/file-types), in case that's of any use to anyone.

**Closed** 2019-06-25 12:38 UTC
Labels: Good for Contribution
