### ISSUE TITLE
lib.mailer should not modify the outgoing message

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2612] opened 2015-09-02 14:37 UTC
Currently mail sent with ckan.lib.mailer will call add_msg_niceties to add content to the start and the end of the email.  

It should send the email unchanged from the caller so that they have more control over the formatting of the email.  For instance, on data.gov.uk we don't want the fallback to the username field.

**Comment by amercader** [comment] 2015-09-03 14:23
Duplicate of https://github.com/ckan/ckan/pull/2465

**Comment by davidread** [comment] 2015-09-03 14:23
@amercader has related PR that fixes this

**Closed** 2015-09-03 14:23 UTC
