### ISSUE TITLE
Adding images via links in organization, group and site logos result on broken URLs

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#5947] opened 2021-03-08 06:47 UTC
**CKAN version**
2.8

**Describe the bug**
When adding images via links or clearing them, result is broken url. 

**Steps to reproduce**
Add image, clear it.

**Expected behavior**
URL should be link itself or nothing if cleared.

**Additional details**
Backporting https://github.com/ckan/ckan/pull/5020 should fix this.

**Comment by Sunny-NEC** [comment] 2021-04-19 11:30
hi , @amercader  i would like to work on this issue.

**Comment by Sunny-NEC** [comment] 2021-05-03 06:42
sir i  setup a ckan 2.9 in my system and it is already fix in the version 2.9. so i stop working in this issue and looking forward to another one.

**Comment by amercader** [comment] 2021-05-14 12:50
@Zharktas I'm not sure #5020 is the right fix for this because that relates to file uploads in Flask, and the group/org controller was not yet migrated in 2.8.
Anyway, I can't reproduce this in 2.8.8b (linked images work fine).

Feel free to reopen if you can reproduce it.

**Closed by amercader** 2021-05-14 12:50 UTC
Labels: Backport 2.8.8, Backport pending
