### ISSUE TITLE
Presence of additional cookies breaks CKAN login

### ISSUE THREAD

**Issue by kjoshi** [ckan/ckan#7700] opened 2023-07-07 15:12 UTC
## CKAN version
2.10.1

## Describe the bug
The presence of additional cookies in JSON format appears to break the `ckan` cookie functionality and CKAN's login flow.

### Steps to reproduce
- `git clone https://github.com/ckan/ckan-docker.git`
- `cd ckan-docker`
- `cp .env.example .env`
- Edit `.env` and set line 33 to: `CKAN_SITE_URL=http://localhost:5000`
- `docker compose -f docker-compose.dev.yml --env-file .env up --build -d`
- Navigate to `http://localhost:5000/user/login`
- Manually remove the `ckan` cookie. (I.e. via `Application > Storage > Cookies > ckan > Delete` in Chrome) (Or alternatively, log in as `ckan_admin:test1234` and wait 10 minutes for the session to expire.
- Manually create a new cookie with name=`test` and value=`{"test": "test"}`
- Try and log in as `ckan_admin:test1234`
- Login fails with no obvious errors. Redirected to `login` page.
- Manually delete the `test` cookie.
- Try and log in again as `ckan_admin:test1234`
- Login succeeds.

### Expected behavior
The presence of other cookies should have no impact on CKAN. In our case we are trying to implement a [cookie control](https://www.civicuk.com/cookie-control/) cookie, which is preventing users from being able to log back in once their session expires. However any cookie in JSON format seems to trigger the problem.

### Additional details
When the browser's cookies are in this state it seems to be impossible to log in without clearing all cookies and starting from scratch:
![image](https://github.com/ckan/ckan/assets/1217533/79e877a5-f709-4635-bfe1-d5bc9e309d96)

Cookies that do not contain JSON do not trigger the problem.

**Comment by kowh-ai** [comment] 2023-07-12 07:08
@kjoshi - I can confirm your findings and indeed it's a JSON format cookie that breaks the login

**Comment by TomeCirun** [comment] 2023-07-17 07:45
This issue is not specific to `Flask-Login`, it also breaks the login on `CKAN 2.9`.

I believe the problem is related to `beaker.session`.

@amercader @kowh-ai

**Comment by amercader** [comment] 2023-07-18 14:34
@TomeCirun @kowh-ai did you test it on the Docker setup as well? I can't reproduce this using the local development server.

@TomeCirun are you using the default beaker settings or cookie-based sessions?

**Comment by kowh-ai** [comment] 2023-07-18 15:10
@amercader - yes Docker, a fresh one of [these](https://github.com/ckan/ckan-docker)

**Comment by TomeCirun** [comment] 2023-07-18 20:49
I tested it using the local development server, and these are my beaker.session settings:

```
beaker.session.key = ckan,
beaker.session.secret = GlAVKu74vwxo3S3doBsoxIvo1lg
beaker.session.validate_key = GlAVKu74vwxo3S3doBsoxIvo1lg
```

@amercader

**Comment by TomeCirun** [comment] 2023-07-19 08:17
> @TomeCirun @kowh-ai did you test it on the Docker setup as well? I can't reproduce this using the local development server.

When testing please check if the path is set to '/' @amercader 

<img width="651" alt="image" src="https://github.com/ckan/ckan/assets/72216462/22f507b5-82b2-494c-bffa-664b2f1ee33b">

**Comment by Pooya-Oladazimi** [comment] 2023-08-09 07:54
I faced a similar issue with ckan 2.9.9
I would share it here, maybe related. I shared it Gitter already.

I recently installed ckan 2.9.9 for a new project. I faced a weird issue with user registration.
My ckan instanse is like: **http://host/root_path**
The issue is after I click the button "Create Account", I redirect to **http://host/user/logout**
It raises 404 because it does not exist
**After that whatever ckan url I try to open, it always redirects to the above URL. I had to delete the browser cache in order to use ckan again**

The issue is somehow related to the cookie that ckan sets after user registration. After I delete that cookie, I am able to open ckan again and log in to it with the created user. 

The weird point for me is that:
**Why does ckan redirect me to logout instead of my dashboard after registration?**
Regardless of the fact that the redirection missed the root_path

As a test, I removed the root_path from ckan.ini and who.ini to see what happens
It does not redirect to logout and 404 but weirdly it redirects to the /user/register page after registration.
with root_path fails like before

PS: Our CKAN is also behind an Nginx reverse Proxy. So when ckan redirects me to "/" (without root_path) It opens the service provider webpage and not our CKAN.

**Comment by Pooya-Oladazimi** [comment] 2023-08-24 07:31
Update:
I reverted back my CKAN instance code to the 2.9.2 version (I had it in one of our internal repositories) and now everything works without a problem. **I did not change any configuration** and only changed the CKAN source code. So I assume something is wrong with the 2.9.9 auth cookie.

**Comment by TomeCirun** [comment] 2023-11-04 18:45
@amercader, I've managed to trace the issue to the `CookieSession` class, if a `JSON` cookie is present, it causes the [self.cookie](https://github.com/bbangert/beaker/blob/1.11.0/beaker/session.py#L652) to become invalidated. The `is_new` flag is set to True, `self.cookie` is empty and it effectively creates a new session.

As a result, we're encountering a problem with Beaker session cookies and their signature validation when a JSON cookie is included in the session data.

For testing purposes, I replaced the `SessionInterface` with `SecureCookieSessionInterface` and it solves the problem.

**Comment by amercader** [comment] 2023-11-07 15:02
Thanks @TomeCirun I finally was able to reproduce it locally, when it worked on Firefox but not on Chrome, which gave me the clue I needed because I was going crazy.
Firefox and Chrome will sent the cookies ordered differently in the `Cookie` header, so assuming we have these ones:

```
ckan=a3...Lg==    // this is a big base64 string
fldt=hide
test={"test":"test"}
```

Firefox might sent `test=; fldt=; ckan=` and Chrome ``fldt=; ckan=; test=`. This is important because if Beaker chokes *after* processing the `ckan` cookie then the login will work (that's why it worked with Firefox for me).

But upon further investigation, it seems like Beaker might not be the culprit here after all:

https://github.com/python/cpython/issues/86111

It's Python's own `SimpleCookie` which doesn't support parsing JSON strings:

```python
from http import cookies

c = cookies.SimpleCookie()
c.load('fldt=hide;test=hello')
print(c)

Set-Cookie: fldt=hide
Set-Cookie: test=hello


c = cookies.SimpleCookie()
c.load('fldt=hide;test={"test":"test"}')
print(c)

Set-Cookie: fldt=hide
```

So that might be difficult to fix (and might happen if replacing Beaker anyway). Perhaps is best to document it and suggest encoding the JSON string somehow to avoid the issue.

**Comment by wardi** [comment] 2023-11-07 15:43
Looks like double-quotes in cookies in response headers parsed by SimpleCookie can only be used to surround the cookie value. If they appear in the value they need to be escaped with `\`, like:

```python
c = cookies.SimpleCookie()
c.load('fldt=hide;test="{\\"test\\":\\"test\\"}"')
print(c)

Set-Cookie: fldt=hide
Set-Cookie: test="{\"test\":\"test\"}"
```
the same as if we had
```python
c = cookies.SimpleCookie()
c['fldt'] = 'hide'
c['test'] = '{"test":"test"}'
print(c)

Set-Cookie: fldt=hide
Set-Cookie: test="{\"test\":\"test\"}"
```

**Comment by wardi** [comment] 2023-11-07 15:57
https://datatracker.ietf.org/doc/html/rfc2109.html#section-4.1 says cookie values must be either a `word` or a `quoted-string`. Those are defined in https://datatracker.ietf.org/doc/html/rfc2068#section-2.2

A JSON object is not a `token` because it contains `tspecials`:
```
token          = 1*<any CHAR except CTLs or tspecials>

tspecials      = "(" | ")" | "<" | ">" | "@"
                 | "," | ";" | ":" | "\" | <">
                 | "/" | "[" | "]" | "?" | "="
                 | "{" | "}" | SP | HT
```
So the only valid way to send JSON as a cookie value is as a `quoted-string`

**Comment by wardi** [comment] 2023-11-07 16:16
I recommend we close this ticket because `{"test": "test"}` is an invalid cookie value per the RFC, and python is doing nothing wrong by ignoring it and any following cookies received from a client.

**Comment by amercader** [comment] 2023-11-08 09:21
I agree, @kjoshi please check the discussion above for context, thanks for the report

**Closed by amercader** 2023-11-08 09:21 UTC
Labels: Backport pending
