### ISSUE TITLE
Datasets page breadcrumb has the wrong URL

### ISSUE THREAD

**Issue by yomatters** [ckan/ckan#4405] opened 2018-08-16 15:03 UTC
### CKAN Version if known (or site URL)
2.8.1

### Please describe the expected behaviour
The "Datasets" breadcrumb on the Datasets page links to `/dataset`.

### Please describe the actual behaviour
The "Datasets" breadcrumb on the Datasets page links to `/dataset_search`. Clicking it produces a 404 error.

### What steps can be taken to reproduce the issue? 
Navigate to `/dataset`, and click on the "Datasets" link in the breadcrumbs.

**Comment by rossjones** [comment] 2018-08-18 09:33
This is easily reproducible on beta.ckan.org (but not demo.ckan.org) so it looks like it may have been a recent change.

**Comment by davidread** [comment] 2019-05-28 20:57
This is a problem on CKAN 2.8.0, 2.8.1 and 2.8.2.

This has been fixed for 2.9.0 by replacing the pylons controller with a flask view: https://github.com/ckan/ckan/pull/4062

I've done a fix for 2.8 here: https://github.com/ckan/ckan/pull/4820

**Comment by gallexme** [comment] 2019-10-21 12:32
any updates? ~5Months later and still no released fix

**Comment by davidread** [comment] 2019-10-21 14:37
@gallexme Didn't #4820 go into the CKAN 2.8.3 release, as per the PR tag?

**Comment by gallexme** [comment] 2019-10-21 17:04
@davidread  no see for yourself: https://demo.ckan.org/dataset

click on the dataset breadcrumb

**Comment by davidread** [comment] 2019-10-21 19:41
@gallexme I believe that's running CKAN 2.8.2, though. The release branch would be a better place to check for it, please.

**Comment by gallexme** [comment] 2019-10-22 09:51
@davidread sorry I seem to have misunderstood the back port to 2.8.3 tag, I thought someone still had to backport it to 2.8.3 cuz it didn't make it

Also I haven't seen anything about the 2.8.3 version here https://docs.ckan.org/en/2.8/changelog.html

So I couldn't check the changelog. 
But apperantly u right and it's 2.8.3, I'm gonna try updating soon

**Comment by davidread** [comment] 2019-10-22 11:02
Closing - fixed in CKAN 2.8.3 
https://docs.ckan.org/en/latest/changelog.html#v-2-8-3-2019-07-03

**Closed by davidread** 2019-10-22 11:02 UTC
