### ISSUE TITLE
Translation issue same as 'https://beta.ckan.org'

### ISSUE THREAD

**Issue by ltf9651** [ckan/ckan#4550] opened 2018-11-10 09:11 UTC
Got a translation trouble with zh_CN
https://beta.ckan.org : the index home page, /user/ , /about/ page and so on won't be translated, and other page can be tranlated.
Why?
I found this from my own app and https://beta.ckan.org

**Comment by amercader** [comment] 2018-11-13 12:14
Duplicate of https://github.com/ckan/ckan/issues/4413

**Closed by amercader** 2018-11-13 12:14 UTC
