### ISSUE TITLE
The "#" character in uploaded CSV files crashes the Data Explorer

### ISSUE THREAD

**Issue by ecraigo** [ckan/ckan#2514] opened 2015-07-02 19:25 UTC
I am using a built-from-source installation of ckan 2.3 on a Mac running OS X 10.10.3. Whenever I upload a .csv resource (through the combined effects of properly-functioning DataStore, FileStore, and DataStorer plugins) that contains, in any cell, a number sign "#", I am not able to visualize the data within it in any way. A look at the JavaScript Console in my Chrome browser finds jQuery.js returning the error:

```
Uncaught Error: Syntax error, unrecognized expression: #
```

Just from looking at the error, it looks as though the input is not being properly escaped before going to the browser.

**Comment by mattfullerton** [comment] 2015-07-07 12:47
This is solved in Recline (https://github.com/okfn/recline/pull/474#event-270438927). This issue is a duplicate of #2490 where the planned fix is also documented.

**Comment by brew** [comment] 2015-07-07 14:09
Thanks @mattfullerton.

**Closed by brew** 2015-07-07 14:09 UTC
