### ISSUE TITLE
Is it possible to install ckan on ubuntu 18.04?

### ISSUE THREAD

**Issue by TheMMcOfficial** [ckan/ckan#4311] opened 2018-06-27 15:35 UTC
### CKAN Version if known (or site URL)
2.8

### Please describe the expected behaviour
If it's possible and how I install it if it's possible.

**Comment by TheMMcOfficial** [comment] 2018-06-29 14:58
Solr is not working for me.

**Comment by rossjones** [comment] 2018-06-29 15:09
It's probably related to the version that is installed on 1804.
You can check with 

```
wget -O- "http://127.0.0.1:8983/solr/admin/registry.jsp" | grep 'solr-spec-version'
```

You're welcome to dive in and help with support for newer Solr ;), or you could see if you can install Solr 3.6 ... http://sysop.volyn.ua/how-to-install-apache-solr-3-6-on-debian-or-ubuntu/

**Comment by kushagrasrivastva-NEC** [comment] 2018-07-04 05:29
Tried docker installation on 1804. Its working fine. Below were the issues faced and resolved: 
1. **sqlachemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column user.password does not exist**
Soln - Remove the postgresql database and installed it again before starting docker installation.

 Ckan working now.
![image](https://user-images.githubusercontent.com/40620966/42258376-03ec0aaa-7f79-11e8-8969-5f3ba3fe0a6a.png)

**Comment by rossjones** [comment] 2018-07-06 08:00
I think the plan is to ensure CKAN works on 18.04 as soon as the opportunity arises, so I'm going to close this issue.  Feel free to continue the discussion on the [ckan-dev](https://lists.okfn.org/mailman/listinfo/ckan-dev) mailing list

**Closed by rossjones** 2018-07-06 08:00 UTC

**Comment by jwoyame** [comment] 2018-09-20 03:51
For the benefit of others who come across this:

I installed CKAN 2.8.1 [from source](https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html) on Ubuntu 18.04, and it works fine. However, Solr produces a 404 from Jetty. The problem is with the `solr-jetty` package on 18.04. It installs `jetty9` which does not observe the `/etc/jetty9/contexts/solr.xml` symlink created by the package (which links to `/etc/solr/solr-jetty.xml`). As a result, Jetty will never see solr.xml in order to serve Solr content.

To fix this problem, simply create the symlink in the `/var/lib/jetty9/webapps/` directory instead:

`$ sudo ln -s /etc/solr/solr-jetty.xml /var/lib/jetty9/webapps/solr.xml`

Reference: https://salsa.debian.org/java-team/lucene-solr/commit/cfe497930a286f641a1d53987e9db3c408c3179d

**Comment by fwoerister** [comment] 2018-09-23 15:09
@jwoyame thanks! you saved me a lot of time :+1:

**Comment by ap-Codkelden** [comment] 2018-11-22 20:42
@jwoyame Thank you! Still actual for me too. 👍

**Comment by dioubernardo** [comment] 2019-05-03 21:36
Plz, help me.
I'm following the ckan installation guide via source on ubuntu 18.04, when installing solr-jetty it does not start

May  3 20:43:02 dados jetty9[21697]: 2019-05-03 20:43:02.014:WARN:oejx.XmlConfiguration:main: Config error at <Call name="addAliasCheck"><Arg>|      <New class="org.eclipse.jetty.server.handler.ContextHandler$ApproveSameSuffixAliases"/>|    </Arg></Call> java.lang.ClassNotFoundException: org.eclipse.jetty.server.handler.ContextHandler$ApproveSameSuffixAliases in file:/etc/solr/solr-jetty.xml

I go to the file /etc/solr/solr-jetty.xml and comment

  


After that the web app starts however when accessing the following error is shown

HTTP ERROR 500
Problem accessing /solr/. Reason:

    Severe errors in solr configuration.

....
Caused by: java.io.IOException: Cannot create directory: /var/lib/solr/data/index
	at org.apache.lucene.store.NativeFSLock.obtain(NativeFSLockFactory.java:172)
	at org.apache.lucene.store.Lock.obtain(Lock.java:72)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1098)
	at org.apache.solr.update.SolrIndexWriter.<init>(SolrIndexWriter.java:84)
	at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:398)
	... 54 more

I try solr-tomcat

and the error is the same

May  3 21:19:16 dados tomcat9[24370]: [] Added SolrEventListener for firstSearcher: org.apache.solr.core.QuerySenderListener{queries=[{q=static firstSearcher warming in
 solrconfig.xml}]}
May  3 21:19:16 dados tomcat9[24370]: [] Solr index directory '/var/lib/solr/data/index' doesn't exist. Creating new index...
May  3 21:19:16 dados tomcat9[24370]: java.lang.RuntimeException: java.io.IOException: Cannot create directory: /var/lib/solr/data/index

both the jetty user and the tomcat user had read and write permissions on the directory /var/lib/solr/data/

I tried to install solr downloading direct from http://www-eu.apache.org/dist/lucene/solr/ versions 6.6.6, 7.7.1 and 8.0.0 and the error was the same

first the step "Replace the default schema.xml file with a symlink to the CKAN schema file included in the sources."  did not work because the file is not supported by the versions of solr

in this versios firts I need edit the file solrconfig.xml  and insert <schemaFactory class="ClassicIndexSchemaFactory"/> to read schema.xml instead of Managed Schema

ERROR: Error CREATEing SolrCore 'test': Unable to create core [test] Caused by: defaultSearchField has been deprecated and is incompatible with configs with luceneMatchVersion >= 6.6.0.  Use 'df' on requests instead.

I tried to ignore the modification of schema.xml  and then solr is executing correctly. but when running the paster

(default) root@dados:/usr/lib/ckan/default/src/ckan# paster serve /etc/ckan/default/production.ini
2019-05-03 21:34:25,898 INFO  [ckan.config.environment] Loading static files from public
2019-05-03 21:34:25,981 ERROR [pysolr] Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
2019-05-03 21:34:25,982 ERROR [ckan.lib.search.common] Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 60, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
SolrError: Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
2019-05-03 21:34:26,002 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
2019-05-03 21:34:26,032 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2019-05-03 21:34:27,598 ERROR [pysolr] Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
2019-05-03 21:34:27,599 ERROR [ckan.lib.search.common] Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/common.py", line 60, in is_available
    conn.search(q="*:*", rows=1)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
SolrError: Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
2019-05-03 21:34:27,601 WARNI [ckan.lib.search] Problems were found while connecting to the SOLR server
2019-05-03 21:34:27,608 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2019-05-03 21:34:27,937 CRITI [ckan.lib.uploader] Please specify a ckan.storage_path in your config
                         for your uploads
Starting server in PID 25826.
serving on 0.0.0.0:5000 view at http://127.0.0.1:5000

**Comment by masudk** [comment] 2020-06-15 15:00
I have written a detailed step-by-step guide on installing ckan by source on Ubuntu 18.04 LTS using Python 3, Nginx and uwsgi [here](http://masudk.com/2020/06/15/setting-up-ckan-on-ubuntu-18-04-python-3-and-amazon-lightsail/ )

Hopefully this would help and save others some time!

**Comment by kowh-ai** [comment] 2020-06-16 02:46
@masudk  - Nice work here - very detailed guide - well done!

**Comment by linforestzhang** [comment] 2020-08-27 15:46
>     1. sqlachemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column user.password does not exist

How did you solve this issue about user.password? Thanks
