### ISSUE TITLE
Add not existing License

### ISSUE THREAD

**Issue by EnxEng** [ckan/ckan#2110] opened 2014-12-03 09:36 UTC
I have tried to add a new license to CKAN.
I followed the documentation:
http://docs.ckan.org/en/943-writing-extensions-tutorial/configuration.html#licenses-group-url

and so, created a new json, by merging it with the one online:
http://licenses.opendefinition.org/licenses/groups/ckan.json

But a have an error, when creating a new dataset:
KeyError: 'is_okd_compliant'

In fact I have noticed from the source code, you changaed somethin in the revisiotns, and in order to make License, transatable, you have diffrent keys, fomr the ones officialy used by ODK.
I notices that all keys are the same, except for:
            'is_generic',
            'is_okd_compliant',
            'is_osi_compliant',

that you use in ckan/model/license.py
where, Open Definition, uses:
  "od_conformance": 
  "osd_conformance".

I think that keys in the source code should be updated.

**Comment by kapucko** [comment] 2015-01-21 08:58
I got the same problem. Do you have a solutions @EnxEng?

**Comment by kapucko** [comment] 2015-01-22 09:07
I added keys 'is_okd_compliant' and 'is_osi_compliant' to each license in json...

**Comment by Conzar** [comment] 2015-04-07 22:23
I have found this error when preparing to demonstrate a different error (with spatial extension).  This error is reproducible here: 
https://bitbucket.org/landcareresearch/vagrant-ckan-spatial-error

**Comment by joetsoi** [comment] 2015-04-13 14:21
yeah the opendefinition license.json is missing is_okd_compliant which causes ckan to break, I will bring it up in tomorrows dev meeting to decided whether we should fix license.json or remove the checks for is_okd_compliant references from ckan.

**Comment by joetsoi** [comment] 2015-04-13 14:35
@Conzar I recommend for now you create a new license.json and set your license_group_url to that you can generate the right one using the ridiculous oneliner

`curl http://licenses.opendefinition.org/licenses/groups/ckan.json | jq 'map(.+{is_okd_compliant: (if .od_conformance == "approved" then true else false end)})' | jq 'map(.+{is_osi_compliant: (if .osd_conformance == "approved" then true else false end)})'`

although I'm sure you could do it in one jq command

**Comment by davidread** [comment] 2015-04-13 17:20
I've done a pull request for moving to the new keys: https://github.com/ckan/ckan/pull/2391
I can't see any reason to be left behind licenses.opendefinition.org

**Comment by metaodi** [comment] 2015-05-27 15:02
@joetsoi @davidread 
It would be nice if http://licenses.opendefinition.org would provide a JSON that can be used for CKAN 2.2 and CKAN 2.3, any chance you could add the missing attributes there (I'm not really sure who is in charge of this site)? Or provide those on ckan.org? I know it's easy to create such a file by myself, but it would be nice to have this in one place and not that everybody has to deal with this separately. WDYT?

**Comment by davidread** [comment] 2015-05-28 23:22
I guess someone at Open Knowledge runs that site, but we've gone down the road of upgrading to their newer format, rather than asking them to revert to their old format. So perhaps you can simple cherry-pick the PR mentioned above and you can use whichever of the formats you like.

**Comment by davidread** [comment] 2015-05-28 23:23
BTW now the PR has been merged, I'm assuming the issue is closed

**Closed by davidread** 2015-05-28 23:23 UTC

**Comment by Conzar** [comment] 2015-08-18 22:26
@davidread The license is still failing on a default ckan 2.3 install.

**Comment by davidread** [comment] 2015-08-19 09:29
@Conzar yes the PR went into the new release 2.4 but was not backported to 2.3 as it was not considered an important bugfix. So you'd need to upgrade.
