### ISSUE TITLE
View scrollbar/window size misalignment

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#2309] opened 2015-02-19 23:17 UTC
Previewing a file in Data Explore view, displays fine, however I notice there are two vertical scroll bars and this causes issues.
![views4](https://cloud.githubusercontent.com/assets/4842751/6278182/a786a84a-b8f9-11e4-8288-53012f7ec78d.png)
If the right most scroll bar is used, the Grid, Graph, Map buttons, and the column headings disappear.
If you use the 'inner' scroll bar then the headings remain, but when you get down the rows eventually you can't scroll any further to the bottom of the grid, and you need to use the right most scroll bar to go down (losing the buttons and headings).
Need to re align the frame sizes... and remove the need for the right most scroll bar?

**Comment by Aaron-M** [comment] 2015-02-23 03:32
Update - I have only noticed this on one dataset/resource
http://beta.ckan.org/dataset/second-attempt-data2/resource/cd61c975-fe0f-46bb-825a-4b63f429918f
Other files of same file format I have previewd and they only had a single vertical scroll bar.

**Comment by Aaron-M** [comment] 2015-02-23 03:51
Update - seems to be something about login and user rights that is triggering this double scroll bar.  This record
http://beta.ckan.org/dataset/second-attempt-data2/resource/7361f92d-1096-41d1-aaed-afab88a2c20e
did not have a view automatically generated, so I manually added the View.  It looked fine, with only a single scroll bar.

However, shortly afterwards I noticed that it suddenly had the double vertical scroll bar problem.I have deduced that the double scroll bar issue is visible if I am not logged in, or if I am logged in under a different username (even one that has manage rights to the dataset):
![scroll1](https://cloud.githubusercontent.com/assets/4842751/6322575/32172cbc-bb7c-11e4-907b-901223ae73f9.png)
![scroll2](https://cloud.githubusercontent.com/assets/4842751/6322576/3217ced8-bb7c-11e4-8cf2-4f938996ce8d.png)

**Comment by Aaron-M** [comment] 2015-02-24 22:49
Prompted by #2317 it dawned on me that in this problem there is also some unusual behaviour in that sometimes the _id field column is not displayed, but other times it is visible - ref images above.

**Comment by JohnnySpace** [comment] 2017-10-13 09:19
@Aaron-M and @amercader we experienced the same problem in 2015:

![fehler_chrome_open-data-portal_2015-02-24_20-21-42](https://user-images.githubusercontent.com/32764664/31538993-850869a4-b007-11e7-98d1-5c5b1c8a0be3.jpg)

Link to dataset: [https://www.opengov-muenchen.de/dataset/behindertenparkplaetze/resource/9a2c7f41-6c52-40c6-bbbd-1ca923afb8d8](url)

I did a retest today with CKAN 2.5.3 an Google Chrome version 61.0.3163.100 and could not reproduce the problem. Can you confirm, that the problem no longer exists / is solved?

**Comment by mattfullerton** [comment] 2017-10-19 08:39
I have something in my head that this only happens with certain window sizes/screen resolutions.

https://github.com/NRGI/resourcedata.org/issues/84

**Comment by tino097** [comment] 2018-09-10 11:03
As this looks like a issue targeting really old release, i will close it. 
Please reopen if occurs in newer versions

**Closed by tino097** 2018-09-10 11:03 UTC
