### ISSUE TITLE
Java NoClassDefFoundError from Jetty on Ubuntu 14.04

### ISSUE THREAD

**Issue by seanh** [ckan/ckan#2019] opened 2014-10-29 17:29 UTC
Jetty fails to start: `java.lang.NoClassDefFoundError: org/apache/tomcat/util/descriptor/LocalResolver`. Package `solr-jetty` is broken in Ubuntu 14.04. Some workarounds documented in this Debian issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740596

**Comment by amercader** [comment] 2015-09-28 14:11
The original bug seems to be fixed according to the link provided.

I've done several installs on Ubuntu 14.04 and can't reproduce this issue so I'm going to close this. @florianm if you have more details feel free to reopen.

For reference, these versions (what you get by default on Ubuntu 14.04) are working for me:

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

```
dpkg -s jetty
Package: jetty
Status: install ok installed
Priority: optional
Section: java
Installed-Size: 1019
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 6.1.26-1ubuntu1.1
Depends: libjetty-java (>= 6.1.26-1ubuntu1.1), adduser, jsvc, apache2-utils, default-jre-headless | java5-runtime-headless
Suggests: libjetty-extra-java (>= 6.1.26-1ubuntu1.1), libjetty-extra (>= 6.1.26-1ubuntu1.1), libjetty-java-doc (>= 6.1.26-1ubuntu1.1)
```

```
dpkg -s solr-jetty
Package: solr-jetty
Status: install ok installed
Priority: optional
Section: java
Installed-Size: 70
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Source: lucene-solr
Version: 3.6.2+dfsg-2
Depends: jetty (>= 6.1.22), libjetty-extra-java (>= 6.1.22), solr-common (= 3.6.2+dfsg-2), default-jdk | java5-sdk
Conflicts: solr-tomcat, solr-tomcat6
```

To test if Solr is working fine do:

    curl "http://127.0.0.1:8983/solr/select?q=*:*"

It should return:

```
<?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader"><int name="status">0</int><int name="QTime">3</int><lst name="params"><str name="q">*:*</str></lst></lst><result name="response" numFound="0" start="0"/>
</response>
```

**Closed by amercader** 2015-09-28 14:11 UTC
Labels: Ubuntu 14.04

**Comment by florianm** [comment] 2015-09-29 00:17
thanks Adrià, all good from my end!
