### ISSUE TITLE
Error in datastore updating resource

### ISSUE THREAD

**Issue by jroigfer** [ckan/ckan#3980] opened 2018-01-08 18:10 UTC
### CKAN Version if known (or site URL)
2.6.3

### Please describe the expected behaviour
Update resource uploading new file should be replace the file.

### Please describe the actual behaviour
Connecting through a vpn to the internal network and accessing the portal to update a resource, the resource always is updated correctly whitout errors, but accessing from the internal network without vpn, when trying to replace the file by updating the resource, an internal server error (500) appears, the datapusher if it updates the resource information well, but in the ckan logs an error appears when executing the sql SELECT alias_of FROM "_table_metadata" WHERE name = :id' in the datastore database:
```
[Mon Jan 08 18:12:50.968429 2018] [:error] [pid 29552] 2018-01-08 18:12:50,968 INFO [ckan.lib.base] /api/3/action/datastore_delete render time 0.110 seconds
[Mon Jan 08 18:12:50.983580 2018] [:error] [pid 29551] res_id:u'a7fc1c26-ac31-46e5-be04-a87499ea1b87'
[Mon Jan 08 18:12:50.983599 2018] [:error] [pid 29551] data_dict:{'connection_url': 'postgresql://xxxxxx:xxxx@localhost/xxxxx', 'limit': 0, 'resource_id': u'a7fc1c26-ac31-46e5-be04-a87499ea1b87'}
[Mon Jan 08 18:12:50.983609 2018] [:error] [pid 29551] results.count:0
[Mon Jan 08 18:12:50.988776 2018] [:error] [pid 29551] [remote ip_remote] Error - <class 'ckan.logic.NotFound'>: Resource "a7fc1c26-ac31-46e5-be04-a87499ea1b87" was not found.
[Mon Jan 08 18:12:50.993765 2018] [:error] [pid 29551] [remote ip_remote] URL: http://ckan_url/dataset/nuevo-dataset-01/resource/a7fc1c26-ac31-46e5-be04-a87499ea1b87
[Mon Jan 08 18:12:50.993776 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/weberror/errormiddleware.py', line 171 in call
[Mon Jan 08 18:12:50.993778 2018] [:error] [pid 29551] [remote ip_remote] app_iter = self.application(environ, sr_checker)
[Mon Jan 08 18:12:50.993780 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/webob/dec.py', line 147 in call
[Mon Jan 08 18:12:50.993781 2018] [:error] [pid 29551] [remote ip_remote] resp = self.call_func(req, *args, **self.kwargs)
[Mon Jan 08 18:12:50.993782 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Mon Jan 08 18:12:50.993784 2018] [:error] [pid 29551] [remote ip_remote] return self.func(req, *args, **kwargs)
[Mon Jan 08 18:12:50.993785 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in call
[Mon Jan 08 18:12:50.993787 2018] [:error] [pid 29551] [remote ip_remote] return request.get_response(self.app)
[Mon Jan 08 18:12:50.993788 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Mon Jan 08 18:12:50.993790 2018] [:error] [pid 29551] [remote ip_remote] application, catch_exc_info=False)
[Mon Jan 08 18:12:50.993791 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Mon Jan 08 18:12:50.993792 2018] [:error] [pid 29551] [remote ip_remote] app_iter = application(self.environ, start_response)
[Mon Jan 08 18:12:50.993794 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/webob/dec.py', line 147 in call
[Mon Jan 08 18:12:50.993795 2018] [:error] [pid 29551] [remote ip_remote] resp = self.call_func(req, *args, **self.kwargs)
[Mon Jan 08 18:12:50.993797 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Mon Jan 08 18:12:50.993798 2018] [:error] [pid 29551] [remote ip_remote] return self.func(req, *args, **kwargs)
[Mon Jan 08 18:12:50.993800 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in call
[Mon Jan 08 18:12:50.993801 2018] [:error] [pid 29551] [remote ip_remote] response = request.get_response(self.app)
[Mon Jan 08 18:12:50.993802 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Mon Jan 08 18:12:50.993804 2018] [:error] [pid 29551] [remote ip_remote] application, catch_exc_info=False)
[Mon Jan 08 18:12:50.993805 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Mon Jan 08 18:12:50.993807 2018] [:error] [pid 29551] [remote ip_remote] app_iter = application(self.environ, start_response)
[Mon Jan 08 18:12:50.993812 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/config/middleware/pylons_app.py', line 245 in inner
[Mon Jan 08 18:12:50.993813 2018] [:error] [pid 29551] [remote ip_remote] result = application(environ, start_response)
[Mon Jan 08 18:12:50.993815 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/beaker/middleware.py', line 73 in call
[Mon Jan 08 18:12:50.993816 2018] [:error] [pid 29551] [remote ip_remote] return self.app(environ, start_response)
[Mon Jan 08 18:12:50.993818 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/beaker/middleware.py', line 155 in call
[Mon Jan 08 18:12:50.993819 2018] [:error] [pid 29551] [remote ip_remote] return self.wrap_app(environ, session_start_response)
[Mon Jan 08 18:12:50.993820 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/routes/middleware.py', line 131 in call
[Mon Jan 08 18:12:50.993822 2018] [:error] [pid 29551] [remote ip_remote] response = self.app(environ, start_response)
[Mon Jan 08 18:12:50.993823 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in call
[Mon Jan 08 18:12:50.993825 2018] [:error] [pid 29551] [remote ip_remote] response = self.dispatch(controller, environ, start_response)
[Mon Jan 08 18:12:50.993826 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
[Mon Jan 08 18:12:50.993828 2018] [:error] [pid 29551] [remote ip_remote] return controller(environ, start_response)
[Mon Jan 08 18:12:50.993829 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 292 in call
[Mon Jan 08 18:12:50.993830 2018] [:error] [pid 29551] [remote ip_remote] res = WSGIController.call(self, environ, start_response)
[Mon Jan 08 18:12:50.993832 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in call
[Mon Jan 08 18:12:50.993833 2018] [:error] [pid 29551] [remote ip_remote] response = self._dispatch_call()
[Mon Jan 08 18:12:50.993834 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
[Mon Jan 08 18:12:50.993836 2018] [:error] [pid 29551] [remote ip_remote] response = self._inspect_call(func)
[Mon Jan 08 18:12:50.993837 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
[Mon Jan 08 18:12:50.993839 2018] [:error] [pid 29551] [remote ip_remote] result = self._perform_call(func, args)
[Mon Jan 08 18:12:50.993840 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
[Mon Jan 08 18:12:50.993842 2018] [:error] [pid 29551] [remote ip_remote] return func(**args)
[Mon Jan 08 18:12:50.993843 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/controllers/package.py', line 1126 in resource_read
[Mon Jan 08 18:12:50.993844 2018] [:error] [pid 29551] [remote ip_remote] return render(template, extra_vars=vars)
[Mon Jan 08 18:12:50.993846 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 174 in render
[Mon Jan 08 18:12:50.993847 2018] [:error] [pid 29551] [remote ip_remote] return cached_template(template_name, render_template)
[Mon Jan 08 18:12:50.993848 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
[Mon Jan 08 18:12:50.993851 2018] [:error] [pid 29551] [remote ip_remote] return render_func()
[Mon Jan 08 18:12:50.993853 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 128 in render_template
[Mon Jan 08 18:12:50.993854 2018] [:error] [pid 29551] [remote ip_remote] return render_jinja2(template_name, globs)
[Mon Jan 08 18:12:50.993856 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 85 in render_jinja2
[Mon Jan 08 18:12:50.993857 2018] [:error] [pid 29551] [remote ip_remote] return template.render(**extra_vars)
[Mon Jan 08 18:12:50.993858 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
[Mon Jan 08 18:12:50.993860 2018] [:error] [pid 29551] [remote ip_remote] return self.environment.handle_exception(exc_info, True)
[Mon Jan 08 18:12:50.993861 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
[Mon Jan 08 18:12:50.993863 2018] [:error] [pid 29551] [remote ip_remote] reraise(exc_type, exc_value, tb)
[Mon Jan 08 18:12:50.993864 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckanext/ckanext-client_theme/ckanext/client_theme/templates/package/resource_read.html', line 3 in top-level template code
[Mon Jan 08 18:12:50.993866 2018] [:error] [pid 29551] [remote ip_remote] {% set res = c.resource %}
[Mon Jan 08 18:12:50.993867 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/templates/package/base.html', line 3 in top-level template code
[Mon Jan 08 18:12:50.993869 2018] [:error] [pid 29551] [remote ip_remote] {% set pkg = c.pkg_dict or pkg_dict %}
[Mon Jan 08 18:12:50.993870 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/templates/page.html', line 1 in top-level template code
[Mon Jan 08 18:12:50.993871 2018] [:error] [pid 29551] [remote ip_remote] {% extends "base.html" %}
[Mon Jan 08 18:12:50.993873 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckanext/ckanext-client_theme/ckanext/client_theme/templates/base.html', line 1 in top-level template code
[Mon Jan 08 18:12:50.993874 2018] [:error] [pid 29551] [remote ip_remote] {% ckan_extends %}
[Mon Jan 08 18:12:50.993876 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/templates/base.html', line 103 in top-level template code
[Mon Jan 08 18:12:50.993877 2018] [:error] [pid 29551] [remote ip_remote] {%- block page %}{% endblock -%}
[Mon Jan 08 18:12:50.993878 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/templates/page.html', line 19 in block "page"
[Mon Jan 08 18:12:50.993880 2018] [:error] [pid 29551] [remote ip_remote] {%- block content %}
[Mon Jan 08 18:12:50.993881 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/templates/page.html', line 22 in block "content"
[Mon Jan 08 18:12:50.993883 2018] [:error] [pid 29551] [remote ip_remote] {% block main_content %}
[Mon Jan 08 18:12:50.993884 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/templates/page.html', line 54 in block "main_content"
[Mon Jan 08 18:12:50.993885 2018] [:error] [pid 29551] [remote ip_remote] {% block pre_primary %}
[Mon Jan 08 18:12:50.993887 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckanext/ckanext-client_theme/ckanext/client_theme/templates/package/resource_read.html', line 22 in block "pre_primary"
[Mon Jan 08 18:12:50.993888 2018] [:error] [pid 29551] [remote ip_remote] {% block resource %}
[Mon Jan 08 18:12:50.993892 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckanext/ckanext-client_theme/ckanext/client_theme/templates/package/resource_read.html', line 24 in block "resource"
[Mon Jan 08 18:12:50.993893 2018] [:error] [pid 29551] [remote ip_remote] {% block resource_inner %}
[Mon Jan 08 18:12:50.993895 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckanext/ckanext-client_theme/ckanext/client_theme/templates/package/resource_read.html', line 76 in block "resource_inner"
[Mon Jan 08 18:12:50.993896 2018] [:error] [pid 29551] [remote ip_remote] {% block data_preview %}
[Mon Jan 08 18:12:50.993898 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckanext/ckanext-client_theme/ckanext/client_theme/templates/package/resource_read.html', line 77 in block "data_preview"
[Mon Jan 08 18:12:50.993899 2018] [:error] [pid 29551] [remote ip_remote] {% block resource_view %}
[Mon Jan 08 18:12:50.993901 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckanext/ckanext-client_theme/ckanext/client_theme/templates/package/resource_read.html', line 91 in block "resource_view"
[Mon Jan 08 18:12:50.993902 2018] [:error] [pid 29551] [remote ip_remote] {% block resource_view_content %}
[Mon Jan 08 18:12:50.993904 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckanext/ckanext-client_theme/ckanext/client_theme/templates/package/resource_read.html', line 101 in block "resource_view_content"
[Mon Jan 08 18:12:50.993905 2018] [:error] [pid 29551] [remote ip_remote] {% snippet 'package/snippets/resource_view.html',
[Mon Jan 08 18:12:50.993907 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/jinja_extensions.py', line 260 in _call
[Mon Jan 08 18:12:50.993908 2018] [:error] [pid 29551] [remote ip_remote] return base.render_snippet(args[0], **kwargs)
[Mon Jan 08 18:12:50.993909 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 75 in render_snippet
[Mon Jan 08 18:12:50.993911 2018] [:error] [pid 29551] [remote ip_remote] renderer='snippet')
[Mon Jan 08 18:12:50.993912 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 174 in render
[Mon Jan 08 18:12:50.993913 2018] [:error] [pid 29551] [remote ip_remote] return cached_template(template_name, render_template)
[Mon Jan 08 18:12:50.993915 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
[Mon Jan 08 18:12:50.993916 2018] [:error] [pid 29551] [remote ip_remote] return render_func()
[Mon Jan 08 18:12:50.993917 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 128 in render_template
[Mon Jan 08 18:12:50.993919 2018] [:error] [pid 29551] [remote ip_remote] return render_jinja2(template_name, globs)
[Mon Jan 08 18:12:50.993920 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 85 in render_jinja2
[Mon Jan 08 18:12:50.993922 2018] [:error] [pid 29551] [remote ip_remote] return template.render(**extra_vars)
[Mon Jan 08 18:12:50.993923 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
[Mon Jan 08 18:12:50.993924 2018] [:error] [pid 29551] [remote ip_remote] return self.environment.handle_exception(exc_info, True)
[Mon Jan 08 18:12:50.993926 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
[Mon Jan 08 18:12:50.993927 2018] [:error] [pid 29551] [remote ip_remote] reraise(exc_type, exc_value, tb)
[Mon Jan 08 18:12:50.993929 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/ckanext/pdfview/theme/templates/package/snippets/resource_view.html', line 15 in top-level template code
[Mon Jan 08 18:12:50.993932 2018] [:error] [pid 29551] [remote ip_remote] {% snippet 'package/snippets/resource_view_filters.html', resource=resource %}
[Mon Jan 08 18:12:50.993933 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/jinja_extensions.py', line 260 in _call
[Mon Jan 08 18:12:50.993935 2018] [:error] [pid 29551] [remote ip_remote] return base.render_snippet(args[0], **kwargs)
[Mon Jan 08 18:12:50.993936 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 75 in render_snippet
[Mon Jan 08 18:12:50.993938 2018] [:error] [pid 29551] [remote ip_remote] renderer='snippet')
[Mon Jan 08 18:12:50.993939 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 174 in render
[Mon Jan 08 18:12:50.993940 2018] [:error] [pid 29551] [remote ip_remote] return cached_template(template_name, render_template)
[Mon Jan 08 18:12:50.993942 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
[Mon Jan 08 18:12:50.993943 2018] [:error] [pid 29551] [remote ip_remote] return render_func()
[Mon Jan 08 18:12:50.993944 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 128 in render_template
[Mon Jan 08 18:12:50.993946 2018] [:error] [pid 29551] [remote ip_remote] return render_jinja2(template_name, globs)
[Mon Jan 08 18:12:50.993947 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/base.py', line 85 in render_jinja2
[Mon Jan 08 18:12:50.993948 2018] [:error] [pid 29551] [remote ip_remote] return template.render(**extra_vars)
[Mon Jan 08 18:12:50.993950 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
[Mon Jan 08 18:12:50.993951 2018] [:error] [pid 29551] [remote ip_remote] return self.environment.handle_exception(exc_info, True)
[Mon Jan 08 18:12:50.993953 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
[Mon Jan 08 18:12:50.993954 2018] [:error] [pid 29551] [remote ip_remote] reraise(exc_type, exc_value, tb)
[Mon Jan 08 18:12:50.993955 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/templates/package/snippets/resource_view_filters.html', line 5 in top-level template code
[Mon Jan 08 18:12:50.993957 2018] [:error] [pid 29551] [remote ip_remote] data-module-fields="{{ h.dump_json(h.resource_view_get_fields(resource)) }}"
[Mon Jan 08 18:12:50.993958 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/lib/helpers.py', line 2022 in rekandes2source_view_get_fields
[Mon Jan 08 18:12:50.993960 2018] [:error] [pid 29551] [remote ip_remote] result = logic.get_action('datastore_search')({}, data)
[Mon Jan 08 18:12:50.993961 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/logic/init.py', line 431 in wrapped
[Mon Jan 08 18:12:50.993963 2018] [:error] [pid 29551] [remote ip_remote] result = _action(context, data_dict, **kw)
[Mon Jan 08 18:12:50.993964 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckan/logic/init.py', line 550 in wrapper
[Mon Jan 08 18:12:50.993965 2018] [:error] [pid 29551] [remote ip_remote] return action(context, data_dict)
[Mon Jan 08 18:12:50.993967 2018] [:error] [pid 29551] [remote ip_remote] File '/usr/lib/ckan/client/src/ckan/ckanext/datastore/logic/action.py', line 445 in datastore_search
[Mon Jan 08 18:12:50.993970 2018] [:error] [pid 29551] [remote ip_remote] 'Resource "{0}" was not found.'.format(res_id)
[Mon Jan 08 18:12:50.993971 2018] [:error] [pid 29551] [remote ip_remote] NotFound: Resource "a7fc1c26-ac31-46e5-be04-a87499ea1b87" was not found.
[Mon Jan 08 18:12:50.993973 2018] [:error] [pid 29551] [remote ip_remote]
```
### What steps can be taken to reproduce the issue? 

- Accessing a concrete CKAN resource
- Go to Administration
- Delete the resource and upload a new one
- Click on update
- The error appears

**Comment by jroigfer** [comment] 2018-02-01 12:01
I have new information about the issue, We had been detect that when a updating process is started from the CKAN web portal in the same network, CKAN execute the next query sometimes (more than one  time):
SELECT alias_of FROM "_table_metadata" WHERE name = :id
Returns more than 0 results in every execution, but in a certain moment (I think that CKAN delete the table to create a new table with te same name  after) return 0 occurrences and raise the exception.
The question is, ¿why only occurs in the same network, and never occurs calling externally using a VPN? for example.

**Comment by smotornyuk** [comment] 2018-02-01 16:14
@jroigfer , thanks for reporting - i'll try to investigate this during next week

**Comment by smotornyuk** [comment] 2018-02-28 13:46
After numerous attempts, I was unable to reproduce this issue. I suspect, that problem can be related to thread execution. Something like slight delay via VPN that allows finishing changes/creation of table inside parallel process/thread, whereas using local network, your request is handled almost instantly when not all changes are committed into db. Could you try to reduce the number of server's threads/processes to just 1 and try to reproduce the error?

**Comment by amercader** [comment] 2020-04-13 10:25
Should have been addressed with https://github.com/ckan/ckan/pull/5255, please reopen otherwise

**Closed by amercader** 2020-04-13 10:25 UTC
