### ISSUE TITLE
db clean freezes

### ISSUE THREAD

**Issue by deniszgonjanin** [ckan/ckan#2306] opened 2015-02-19 20:38 UTC
`paster db clean` freezes. This is on master. It has bothered me for a few weeks, but I thought it was due to my own changes. Today I tried it on a clean CKAN install and I can't seem to figure out what the problem is. Would appreciate if someone else could give it a shot to confirm that this is an issue.

**Comment by joetsoi** [comment] 2015-02-20 01:46
paster db clean seems fine to me. Tell me the exact commit you are on. Additionally when it freezes, you should run a ```select * from pg_stat_activity;``` on the database and paste the output here. If there are several connections with one that is idle in transaction then we have a problem. 

It'd be great to know that query the idle on is executing then we can really narrow down what is going on.

**Comment by deniszgonjanin** [comment] 2015-02-25 15:57
Thanks @joetsoi. Below is the output of `pg_stat_activity` on the ckan database when `db clean` freezes

```
ckan=# select * from pg_stat_activity;
 datid | datname | pid | usesysid | usename  | application_name | client_addr  | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | waiting |        state        |                                                                                  query
-------+---------+-----+----------+----------+------------------+--------------+-----------------+-------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+---------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 12037 | ckan    |  16 |    12036 | ckan     |                  | 172.17.0.245 |                 |       35447 | 2015-02-25 15:43:08.559662+00 | 2015-02-25 15:43:09.464309+00 | 2015-02-25 15:43:09.52271+00  | 2015-02-25 15:43:09.523005+00 | f       | idle in transaction | SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.revision_id AS system_info_revision_id +
       |         |     |          |          |                  |              |                 |             |                               |                               |                               |                               |         |                     | FROM system_info                                                                                                                                                        +
       |         |     |          |          |                  |              |                 |             |                               |                               |                               |                               |         |                     | WHERE system_info.key = 'ckan.main_css'                                                                                                                                 +
       |         |     |          |          |                  |              |                 |             |                               |                               |                               |                               |         |                     |  LIMIT 1
 12037 | ckan    |  17 |    12036 | ckan     |                  | 172.17.0.245 |                 |       35450 | 2015-02-25 15:43:09.469598+00 |                               | 2015-02-25 15:43:26.226037+00 | 2015-02-25 15:43:26.226288+00 | f       | idle                | ROLLBACK
 12037 | ckan    |  71 |    12036 | ckan     |                  | 172.17.0.246 |                 |       40456 | 2015-02-25 15:48:31.486067+00 | 2015-02-25 15:48:32.929231+00 | 2015-02-25 15:48:32.929567+00 | 2015-02-25 15:48:32.929579+00 | t       | active              |                                                                                                                                                                         +
       |         |     |          |          |                  |              |                 |             |                               |                               |                               |                               |         |                     | DROP TABLE system_info_revision CASCADE
 12037 | ckan    |  54 |       10 | postgres | psql             |              |                 |          -1 | 2015-02-25 15:45:55.571892+00 | 2015-02-25 15:54:37.225046+00 | 2015-02-25 15:54:37.225046+00 | 2015-02-25 15:54:37.225062+00 | f       | active              | select * from pg_stat_activity;
(4 rows)

```

**Comment by joetsoi** [comment] 2015-02-25 16:18
this sounds familiar, can you consistently reproduce this? I can't remember the specifics as to why this one occured. Try adding `meta.Session.commit()` after this [line](https://github.com/ckan/ckan/blob/111ddfe7140bcf9d21739117b6cfdc44a6057e34/ckan/model/system_info.py#L31) and see if prevents the problem.

**Comment by deniszgonjanin** [comment] 2015-02-25 16:28
Yes, that did fix it

**Comment by joetsoi** [comment] 2015-02-25 16:36
well that's the hack fix, I'll see if I can find the real place it should be fixed, either the callee of `get_system_info` needs to handle it's sqlalchemy session correctly or we need to pass in the session from some context.

What did you do to make this recreatable, so I can take a deeper look another time?

**Comment by deniszgonjanin** [comment] 2015-02-25 16:41
Well to me it's been happening every time. The biggest difference in my dev environment is that my postgres is running on a remote address, not locally. Not sure why that would cause any problems.

Also, datastore is enabled.

**Comment by joetsoi** [comment] 2015-03-03 12:13
I forgot @deniszgonjanin is it possible to get a full traceback? I can't recreated this as it doesn't seem to run through the wsgi initialization for me.

**Comment by deniszgonjanin** [comment] 2015-03-03 20:28
There's no traceback to speak of, as the command just freezes and gets stuck. But I'll poke around and try to find some more clues and post back here.

**Comment by joetsoi** [comment] 2015-03-03 22:14
if you could insert an `import pdb; pdb.set_trace` before the line I suggested  adding a `meta.Session.commit` and run a `w` / `where` that should give me everything I need to fix it.

**Comment by deniszgonjanin** [comment] 2015-03-05 00:14
Ok, this is interesting. I've found something new. It seems that the command freezes when the CKAN web process is already running. That is, if I'm running CKAN with paster (even though it's idle), the `db clean` command will freeze (without your fix above, that is).

If I run `db clean` with CKAN stopped, everything is fine.

As to your suggestion of putting a breakpoint, when CKAN is stopped and the command works, that particular line never gets triggered for whatever reason. But, I killed my postgres process instead to make the command fail, and here is the trace from that

```
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/project/ckan/ckan/lib/cli.py", line 226, in command
    model.repo.clean_db()
  File "/project/ckan/ckan/model/__init__.py", line 238, in clean_db
    meta.metadata.drop_all()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3344, in drop_all
    tables=tables)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1555, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1202, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 119, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
    self.traverse_single(table, drop_ok=True)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 119, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 823, in visit_table
    self.connection.execute(DropTable(table))
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 727, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 67, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 781, in _execute_ddl
    compiled
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (DatabaseError) error with no message from the libpq '\nDROP TABLE user_following_group CASCADE' {}
```

**Comment by wardi** [comment] 2015-03-05 00:20
Oh. that's not a bug then, it's just postgres doing its normal locking thing. You can't drop a table while anyone has a transaction open that read from it (and maybe other situations I don't have a perfect understanding of postgres locking)

How about dropping the DB instead, or just make sure nothing is connected to a database you're wiping.

Shall we just close this issue?

**Comment by deniszgonjanin** [comment] 2015-03-05 00:23
Yes indeed. Sorry for the waste of time. I'm wondering though - what is it about @joetsoi's fix [above](https://github.com/ckan/ckan/issues/2306#issuecomment-75990444) that makes this work?

**Comment by wardi** [comment] 2015-03-05 00:25
Good point. Maybe we're just holding a transaction open forever otherwise? That's probably a good thing to fix

**Comment by joetsoi** [comment] 2015-03-05 12:09
at a guess it's because https://github.com/ckan/ckan/blob/master/ckan/config/middleware.py#L63 gets called outside the standard web request loop cycle, which handles closing of the transaction for us normally, I'm assuming as this is during setup that we end up with an open transaction that doesn't get closed. We probably have the "select * system_info" idle in transaction whenever you start up paster serve

**Comment by rossjones** [comment] 2018-06-06 16:14
I think it's safe to close this issue now.

**Closed** 2018-06-07 07:41 UTC
