### ISSUE TITLE
Internationalization issues

### ISSUE THREAD

**Issue by SilviuPantelimonSay10** [ckan/ckan#6499] opened 2021-10-25 13:54 UTC
**CKAN version**

2.9.4

**Describe the bug**
There is an error for some translations, e.g. romanian, that result in a 500 error on a route for i18n.

**Additional details**
I found the source in ckan/views/api.py and ckan/lib/i18n.py and corrected it. I thought I should let you know.
![image](https://user-images.githubusercontent.com/25910221/138707309-8087b611-b551-4902-90a8-2ee72a66ecbe.png)
![image](https://user-images.githubusercontent.com/25910221/138707455-44dba97b-d352-4470-98e9-eed842ac864e.png)
I should mention that I use Ckan in Docker, and though I don't know why, it uses python2 instead of python3.

**Comment by tomeksabala** [comment] 2022-02-22 12:49
The issue is partially fixed with https://github.com/ckan/ckan/issues/6531
It only fixes the non py2 compatible `open` function use in the `ckan/views/api.py`. The `i18n` module still uses py3 only code.

**Closed as completed** 2024-05-18 09:50 UTC
