### ISSUE TITLE
 requirements.txt automatic checks

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#4659] opened 2019-02-18 12:53 UTC
I suggest to use one of the following services to look for outdated/insecure libraries and automatically create pull requests, so Travis can automatically execute the tests:
- https://pyup.io
- https://requires.io

**Comment by smotornyuk** [comment] 2019-02-19 12:19
Duplicate of #3904 . 
TLDR: we want to remove old libraries before adding this feature

**Comment by amercader** [comment] 2019-02-19 12:36
Yes, as @smotornyuk mentions we are stuck with some old dependencies for various reasons (although we are making good progress at getting rid of those) so the checks wouldn't be accurate. Once we settle on modern versions we can turn this on.

**Closed by amercader** 2019-02-19 12:36 UTC
