### ISSUE TITLE
DataPusher called multiple times when creating a dataset

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#2856] opened 2016-01-28 11:55 UTC
When you upload a CSV the DataPusher [gets called](https://github.com/ckan/ckan/blob/master/ckanext/datapusher/plugin.py#L98) to do its thing.
On https://github.com/ckan/ckan/pull/2234 we added a couple of calls to `resource_patch` on `datastore_create` and `datastore_delete` to set the `datastore_active` extra on the resource.

This is all very well but this update on the resource triggers again the DataPusher, which pings `datastore_delete` and `datastore_create`, which trigger...

Not sure how we can handle this on the `notify` extension point, as we only get the model object there.

**Comment by amercader** [comment] 2016-01-28 12:17
And for the record, before 2.5, DataPusher always got called 2 times when creating a dataset because the wonderful [`new_resource`](https://github.com/ckan/ckan/blob/master/ckan/controllers/package.py#L608) action from the package controller first calls `resource_create` and then `package_update`.

**Comment by Xenros** [comment] 2016-03-10 10:10
Hi, may i know is the problem solve the ? My ckan is install on ubuntu 12.10 with ckan version 2.5.1 
I have successfully install datapusher and datastore. But something when i upload a dataset, datapusher always got called 2 times. This error happened randomly, sometime it push normally but most of the time it pushes twice.

Just like amercader said, I check the log, most of the api got call twice when i upload a dataset. Such as store_create,datastore_delete, datastore_search etc. But teach me if there is any solution for this. Thank you

**Comment by amercader** [comment] 2016-03-16 14:14
@TkTech I'm working on a patch for this, so grabbing it from you

**Comment by NicolaiMogensen** [comment] 2016-04-06 06:55
Is this fixed in 2.5.2? 

I had this error happen for larger datasets (CSV) where the datapusher would run infinitely. (As you describe in the first post)
![datapusher](https://cloud.githubusercontent.com/assets/11227437/14308248/4277e55c-fbd5-11e5-8ece-1522d41ce26a.png)

**Comment by amercader** [comment] 2016-04-06 08:17
@NicolaiMogensen the patch was included in 2.5.2. Can you confirm you are running this version? Also are you using a package install? if not you might need to update the DataPusher itself manually to the latest version.

If you are running the latest of everything can you increase the log level to DEBUG and paste the output somewhere (or send it to me). Thanks

**Comment by NicolaiMogensen** [comment] 2016-04-06 08:56
@amercader We are running a production site on 2.5.1. I am currently updating a parallel site to use 2.5.2 and will update with results once i can replicate the database with datastore and datapusher.

I am using package install, and the DataPusher worked fine in 2.4.x. Will keep you posted :)

**Comment by NicolaiMogensen** [comment] 2016-04-06 09:25
@amercader Ran the same dataset using the datapusher on the newly installed 2.5.2 and i had no problems what so ever!

Will update when i can update the production site aswell. Thanks for the fix, it seems like it's working :)

I added the log, seems like it's doing what it's supposed to, doesn't create and delete twice (Or infinitely for that matter) either.
`[Wed Apr 06 11:18:13 2016] [error] /usr/lib/ckan/datapusher/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '048f83e8-06d1-4340-8ed8-1..$
[Wed Apr 06 11:18:13 2016] [error]   (util.ellipses_string(value),))
[Wed Apr 06 11:18:13 2016] [error] Fetching from: "I removed the link to protect the datasource"
[Wed Apr 06 11:18:28 2016] [error] Deleting "eca1f776-8791-4e0d-a36e-56de72787deb" from datastore.
[Wed Apr 06 11:18:28 2016] [error] Determined headers and types: [{'type': u'text', 'id': u'FID'}, {'type': u'text', 'id': u'wkb_geometry'}, {'type': u'numeric', 'id': u'id'}, {'type': u'text', 'id': u'vejid'},$
[Wed Apr 06 11:18:29 2016] [error] Saving chunk 0
[Wed Apr 06 11:18:30 2016] [error] Saving chunk 1
[Wed Apr 06 11:18:31 2016] [error] Saving chunk 2
[Wed Apr 06 11:18:32 2016] [error] Saving chunk 3
[Wed Apr 06 11:18:32 2016] [error] Saving chunk 4
[Wed Apr 06 11:18:33 2016] [error] Saving chunk 5
[Wed Apr 06 11:18:34 2016] [error] Saving chunk 6
[Wed Apr 06 11:18:35 2016] [error] Saving chunk 7
[Wed Apr 06 11:18:36 2016] [error] Saving chunk 8
[Wed Apr 06 11:18:36 2016] [error] Saving chunk 9
[Wed Apr 06 11:18:37 2016] [error] Saving chunk 10
[Wed Apr 06 11:18:38 2016] [error] Saving chunk 11
[Wed Apr 06 11:18:39 2016] [error] Saving chunk 12
[Wed Apr 06 11:18:39 2016] [error] Saving chunk 13
[Wed Apr 06 11:18:40 2016] [error] Saving chunk 14
[Wed Apr 06 11:18:41 2016] [error] Saving chunk 15
[Wed Apr 06 11:18:42 2016] [error] Saving chunk 16
[Wed Apr 06 11:18:42 2016] [error] Saving chunk 17
[Wed Apr 06 11:18:43 2016] [error] Saving chunk 18
[Wed Apr 06 11:18:44 2016] [error] Saving chunk 19
[Wed Apr 06 11:18:44 2016] [error] Successfully pushed 4940 entries to "eca1f776-8791-4e0d-a36e-56de72787deb".`

**Comment by NicolaiMogensen** [comment] 2016-04-06 13:36
@amercader Promised i would come back with an update. **2.5.2** also fixes this problem on our production server!

Great work :+1:

**Comment by linuxitux** [comment] 2016-05-17 17:52
Hello @amercader, I did a fresh install from sources through "git clone" (for CKAN and the DataPusher) and I'm having the same issue: the datapusher it's cycling forever. My current version is 2.5.2. Can you please help me?

Thanks in advance.

![ckan-error](https://cloud.githubusercontent.com/assets/15108302/15333099/b139fdf2-1c3e-11e6-8542-72b8b364efeb.png)
![ckan-datastore-error](https://cloud.githubusercontent.com/assets/15108302/15333119/c0ca6932-1c3e-11e6-8eb6-05d126386f77.png)

**Comment by inghamn** [comment] 2016-05-18 14:53
I am also still having this problem with 2.5.2 source install.

Is there some different branch we should pull from?

**Comment by inghamn** [comment] 2016-05-18 19:39
I believe something in the datapusher upload process is altering the resource URLmid-process, causing a new upload process to start.

**Comment by inghamn** [comment] 2016-05-19 15:36
It turns out, it's not the URL changing, but rather unexpected response codes when running CKAN behind SSL.  This might be something for the datapusher project, but the issue is documented here.

We also have the InsecurePlatformWarning when enabling SSL for CKAN.
https://github.com/ckan/datapusher/issues/83

The SSL warning cases a response that this CKAN patch considers a failure state, resulting in infinite reattempts.  Datapusher does successfully clear and save the resouce in the datastore.  However, under SSL, the response is not the hard-coded, expected 200 or 201.

Should we expand the range of what is considered a success response?
The code is in /datapusher/jobs.py

Is there a way we can add testing for this situation using SSL-only and a self-signed certificate for CKAN.

**Comment by linuxitux** [comment] 2016-05-19 15:49
@inghamn I'm not using SSL, just plain HTTP. And this only happens with .xls or .cvs files.

**Comment by inghamn** [comment] 2016-05-19 16:16
I have also been able to trigger it without SSL, but using a CSV file in ISO 8859-1 encoding.  When the file includes non-utf8 special characters, the infinite loop is triggered.  If I convert the file to UTF-8 encoding (converting or deleting any special characters), datapusher considers the file upload a success and does not retry

I speculate that this is also part of jobs.py.  Datapusher tries to download the newly uploaded file, to confirm everything worked.  I believe CKAN is converting the file to UTF-8 when the file is received.  Thus, whe datapusher compares the newly downloaded file with the hash of the original ISO 8859-1 file, the hashes are different, and a retry is triggered.

**Comment by linuxitux** [comment] 2016-05-19 16:31
@inghamn uploaded an UTF-8 encoded CVS file without special chars and still happens.

**Comment by davidread** [comment] 2016-05-19 16:41
Perhaps you need to ignore package notifications that don't involve a change in resource.url? I recently did some code for that that you might wish to reuse? See:

https://github.com/ckan/ckanext-archiver/pull/28/files

**Comment by FacundoAdorno** [comment] 2016-05-19 16:45
I have the same problem in my CKAN instance. I'm using the latest CKAN v2.5.2 and when I finish to add a dataset with a csv file, the datapusher begins to push "quasi" infinitely this csv. Due to this, the ckan log grows a lot and the resource preview remains inaccesible by a while.

In my humble opinion, I think that the logic of the datapusher extension is good. I think that the "problem" is in the CKAN source code. Viewing the CKAN log and understanding the CKAN base code, I've noticed an inconsistence in the manner where the "now" datetime is requested. In some places of the code, the "now" time is calculated using the [datetime.utcnow](https://docs.python.org/2/library/datetime.html#datetime.datetime.utcnow) function, and in other places using the [datetime.now](https://docs.python.org/2/library/datetime.html#datetime.datetime.now) function. This causes that, if your local datetime is different that the UTC (for example, [UTC-3](http://www.timeanddate.com/time/zone/argentina/buenos-aires) in my case), the "now" datetime differs depending the manner it is requested.

Particularly, considering this issue, a resource is resubmitted to the datastore (at [this line](https://github.com/ckan/ckan/blob/32375f2d07635db89606cfd150886b80e67a58b4/ckanext/datapusher/logic/action.py#L209) if I'm not wrong) when the resource _'last_modified_datetime'_ is greater than the _'task_created_datetime'_. When a resource is uploaded to a dataset, the ckan/lib/uploader.py modifies the resource['last_modified'] date using the `datetime.utcnow` (at [this line](https://github.com/ckan/ckan/blob/32375f2d07635db89606cfd150886b80e67a58b4/ckan/lib/uploader.py#L204)). When a datapusher task is created and submited, it sends between its data the ['task_created' date](https://github.com/ckan/ckan/pull/2921/files#diff-7b81d8fca5028033fc446f46a76272a7R112) using the task['last_modified'] date as value; this last date is initialized using the `datetime.now` (by default at the [task_status.py](https://github.com/ckan/ckan/blob/32375f2d07635db89606cfd150886b80e67a58b4/ckan/model/task_status.py#L19) or explicitely at [this line](https://github.com/ckan/ckan/blob/32375f2d07635db89606cfd150886b80e67a58b4/ckanext/datapusher/logic/action.py#L77)). When comparing this dates, the datapusher pushes the resource to the datastore until the _'last_modified_datetime'_ be lesser than the _'task_created_datetime'_.

To solve this particular issue, I've modified (and compiled) the uploader.py in [this line](https://github.com/ckan/ckan/blob/32375f2d07635db89606cfd150886b80e67a58b4/ckan/lib/uploader.py#L204) with the following:
```
resource['last_modified'] = datetime.datetime.now()
```

Doing this change, the datapusher will finish with this odd behaviour. In my case, it works.

**Comment by linuxitux** [comment] 2016-05-19 18:00
@FacundoAdorno thank you very much! That solved the issue. The only thing is, in the site, it still says "last modified: 6 hours ago". Maybe we should use datetime.now() instead of datetime.utcnow() in both sides?

**Comment by TkTech** [comment] 2016-05-19 18:05
Internally times should always be in in utc using `utcnow()`, the template should be doing the conversion to the local tz.

**Comment by inghamn** [comment] 2016-05-20 13:32
@TkTech  does this mean the task_created data should be UTC, then?

```python
    task = {
        'entity_id': res_id,
        'entity_type': 'resource',
        'task_type': 'datapusher',
        'last_updated': str(datetime.datetime.utcnow()),
        'state': 'submitting',
        'key': 'datapusher',
        'value': '{}',
        'error': '{}',
    }
```

**Comment by TkTech** [comment] 2016-05-20 18:24
In a perfect world yes, you don't want any internally stored timestamps to be tz-dependant. Even if it's user-generated, you store a utc timestamp and the timezone separately.

**Comment by amercader** [comment] 2016-05-24 11:13
@linuxitux @FacundoAdorno @inghamn @TkTech 
Apologies for the late reply on this. Without having investigating it in depth, the UTC timestamp discrepancy seems to be the most likely culprit. We should be really using UTC everywhere internally so rather than @FacundoAdorno approach of changing the resource last_modified date to use `.now()` I'd like to try using `.utcnow()` on datapusher's action.py. Can you check if the patch below fixes the issues when uploading new resources?

```diff
diff --git a/ckanext/datapusher/logic/action.py b/ckanext/datapusher/logic/action.py
index 8ce97c2..5afb4b0 100644
--- a/ckanext/datapusher/logic/action.py
+++ b/ckanext/datapusher/logic/action.py
@@ -74,7 +74,7 @@ def datapusher_submit(context, data_dict):
         'entity_id': res_id,
         'entity_type': 'resource',
         'task_type': 'datapusher',
-        'last_updated': str(datetime.datetime.now()),
+        'last_updated': str(datetime.datetime.utcnow()),
         'state': 'submitting',
         'key': 'datapusher',
         'value': '{}',
@@ -119,7 +119,7 @@ def datapusher_submit(context, data_dict):
                  'details': str(e)}
         task['error'] = json.dumps(error)
         task['state'] = 'error'
-        task['last_updated'] = str(datetime.datetime.now()),
+        task['last_updated'] = str(datetime.datetime.utcnow()),
         p.toolkit.get_action('task_status_update')(context, task)
         raise p.toolkit.ValidationError(error)
 
@@ -134,7 +134,7 @@ def datapusher_submit(context, data_dict):
                  'status_code': r.status_code}
         task['error'] = json.dumps(error)
         task['state'] = 'error'
-        task['last_updated'] = str(datetime.datetime.now()),
+        task['last_updated'] = str(datetime.datetime.utcnow()),
         p.toolkit.get_action('task_status_update')(context, task)
         raise p.toolkit.ValidationError(error)
 
@@ -143,7 +143,7 @@ def datapusher_submit(context, data_dict):
 
     task['value'] = value
     task['state'] = 'pending'
-    task['last_updated'] = str(datetime.datetime.now()),
+    task['last_updated'] = str(datetime.datetime.utcnow()),
     p.toolkit.get_action('task_status_update')(context, task)
 
     return True
@@ -175,7 +175,7 @@ def datapusher_hook(context, data_dict):
     })
 
     task['state'] = status
-    task['last_updated'] = str(datetime.datetime.now())
+    task['last_updated'] = str(datetime.datetime.utcnow())
 
     resubmit = False
```

In any case I also want to check the issues with encoding you mention @inghamn as I haven't been able to replicate them. Can you paste a link or DM one of the files that is failing for you? Thanks

**Comment by inghamn** [comment] 2016-05-24 13:25
Success! After updating action.py with the patch, I am no longer having the infinite resubmission.

I have tried with my previous ISO-8859 file and do receive the character set mismatch error, but there is no longer a resubmit attempt.  I've attached my CSV files, just in case you still want a copy.

[ckan.zip](https://github.com/ckan/ckan/files/279607/ckan.zip)

**Comment by amercader** [comment] 2016-05-24 13:41
@inghamn great, I'll send a PR with the patch

**Comment by amercader** [comment] 2016-05-24 13:42
@inghamn or feel free to do it yourself if you have the time!

**Comment by amercader** [comment] 2016-05-25 10:27
PR here #3051

**Closed** 2016-08-26 10:45 UTC
Labels: Backport 2.5.3, Bug, DataPusher, DataStore

**Comment by m1h** [comment] 2016-11-21 16:34
We encountered the same issue while using CKAN 2.5.3 (source-install). "Fetching", "deleting", "determining headers and types", "saving chunk", "successfully saved"  is repeating continuously (endless loop). A screenshot:

![ckan-error](https://cloud.githubusercontent.com/assets/10198211/20490877/c081e7d8-b00f-11e6-9181-ff99469a16a6.png)

It is strange that the date returns -1 although the field 'last_modified' in package_show (from action-api) looks the following:  
`"last_modified": "2016-11-21T17:16:11.247765"`


However, if I open the details (from the screenshot above) I get following: 
![ckan_error_info](https://cloud.githubusercontent.com/assets/10198211/20491042/63be23d0-b010-11e6-8ad1-9279870ec5af.png)

So, here the timestamp is correct. Could it be a problem with the date? Does anyone have any suggestion for solving it?

**Comment by wardi** [comment] 2016-12-07 16:26
@m1h try the fix in #3331

**Comment by amercader** [comment] 2017-01-03 11:45
@m1h did #3331 help?

**Comment by mhartlauer** [comment] 2017-01-11 12:32
@amercader: No, unfortunately!

We figured out following: 
The first time a ressource is uploaded to datastore, it works. So, when a new ressource is created, it automatically uploads it to datastore - perfect. However, when one re-uploads it to datastore (via button-click in web-frontend), it is resulting then in an endless loop.

**Comment by janantk** [comment] 2017-03-07 15:34
Hi, we have the same problem with endless loop, appearing very often when we try to delete some resource (other than the last one in the list of package resources) via web interface. CKAN/DataPusher start looping and the resource is never actually deleted. 

We are using CKAN 2.5.3 with #3331 applied, and DataPusher 0.0.10.
