### ISSUE TITLE
user_invite crashes if generated password does not validate

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#4986] opened 2019-09-17 05:37 UTC
The `user_invite` function generates a hidden password that will pass the built-in validators, but if custom validators are supplied and the generated password fails, the function will crash with a KeyError ('password' does not exist in the error dict).

Furthermore, code review suggests that if the crash were fixed, it would be in danger of an infinite loop, constantly generating passwords that are not accepted.

### CKAN Version if known (or site URL)

CKAN 2.8.3

### Please describe the expected behaviour

Inviting a new member, identified by email address, to join an organisation, should result in an email to that address.

### Please describe the actual behaviour

Internal server error. Stack trace shows that this is a `KeyError: ('password',)` in `user_password_validator`.

### What steps can be taken to reproduce the issue?

- Add a password validator that requires non-alphanumeric symbols.
- Go to an organisation, select Manage-Members.
- Select an email address and Add Member.

**Comment by ThrawnCA** [comment] 2019-09-17 05:44
It seems to me that there are several fixes that should be applied:

- `user_password_validator` should initialize the `password` error key if it does not exist.
- Alternatively, `user_invite` should populate the `errors` dict with a blank `password` key before passing it to the validator function.
- The `test_validators` class should be updated with tests that pass in empty `errors` dictionaries.
- `user_invite` should limit the number of times it will retry password generation if validation fails.
- `user_invite` should use a stronger password generation mechanism; the current implementation never uses non-alphanumeric symbols, so it will always fail some types of custom validation.

**Comment by ThrawnCA** [comment] 2019-09-17 06:01
Note that CKAN 2.7 handled the error somewhat more gracefully, displaying the validation failure on-screen, but still had no way to fix the problem if the validators were too strict for the password generation code.

**Comment by wardi** [comment] 2019-09-19 13:24
Two proposals from our developer call on resolving this one:

1. Change the way invites work so that they send a token that allows the user to create a new account with specific permissions (don't create the user with a fake password and reuse the password reset tokens)

2. Add a "password_disabled" option to `user_create` to allow creating a user with no password set (stored as an invalid hash that no password would match) This could be used for other accounts that don't need a password, such as the site user and users authenticated through other services.

**Comment by ThrawnCA** [comment] 2019-09-20 07:22
Those would be good fixes too.

**Comment by wardi** [comment] 2019-09-20 12:02
@ThrawnCA marked as good for contribution, if you have time to work on either approach I'm happy to review and merge. :-)

**Comment by Chandradeep-NEC** [comment] 2020-07-09 04:19
@wardi @ThrawnCA 
We would like to work on this issue. Please me know if no one is working on this.

**Comment by ThrawnCA** [comment] 2020-07-09 04:38
@Chandradeep-NEC No, no progress here. Go ahead.

**Comment by Gauravp-NEC** [comment] 2020-07-14 05:28
@ThrawnCA, I am trying to reproduce the issue. I am facing issue related to SMTP server. I have configure SMTP server on my local machine. When I tried to add a member via email, Internal server error appear on GUI and invitation is not received on the entered email address, but user is created on GUI. To confirm the same I have configure external SMTP server and tried to add a member, Internal sever error did not appear on GUI  this time and invitation is received on the entered email address and user is created. Which SMTP server approach you have taken while producing the issue?

**Comment by ThrawnCA** [comment] 2020-07-14 06:51
Are you using a custom password validator? If you use the standard built-in validator, then it will work.

**Comment by Gauravp-NEC** [comment] 2020-07-16 05:12
@ThrawnCA, Please confirm as have you written a new function for user_password_validator to get custom password validator?

**Comment by ThrawnCA** [comment] 2020-07-16 11:50
@Gauravp-NEC Yes; see https://github.com/qld-gov-au/ckan-ex-qgov/blob/master/ckanext/qgov/common/intercepts.py (probably not the most elegant way to implement it, but the same problem would arise with any other implementation that imposed stricter complexity requirements).

**Comment by Gauravp-NEC** [comment] 2020-07-18 07:11
@ThrawnCA I am unable to reproduce this issue. I have added the "user_password_validator" function from https://github.com/qld-gov-au/ckan-epyx-qgov/blob/master/ckanext/qgov/common/intercepts.py in the original ckan source code file "validators.py"(https://github.com/ckan/ckan/blob/master/ckan/logic/validators.py) to reproduce the issue.

![image](https://user-images.githubusercontent.com/66116382/87847139-37620400-c8f3-11ea-8829-799597a379bb.png)

**Comment by Gauravp-NEC** [comment] 2020-07-28 09:13
@ThrawnCA @wardi , I have raise a PR for updating password validator functionality and also for generating a special character in password from user_invite function. Issue link: https://github.com/ckan/ckan/issues/5512 , PR link: https://github.com/ckan/ckan/pull/5514 . This PR is a part of issue 4986 so i'm adding the link here. Can you please check it.

**Comment by Gauravp-NEC** [comment] 2021-06-30 10:28
@wardi , as you suggested the way to solve this issue in comment https://github.com/ckan/ckan/issues/4986#issuecomment-533128823 no work have been done till now by anyone and this issue is open for so long. 

I suggest that we should change the logic of def user_invite() in such a way that random password generated by it will never fail for any custom validation. Please let me know your opinion. If you agree I will raise the PR for it.

**Comment by wardi** [comment] 2021-07-01 17:31
@Gauravp-NEC that would fix the problem only until someone comes up with a new password validation that doesn't work with these generated passwords. So it doesn't really fix the problem.

**Closed** 2022-06-17 14:03 UTC
Labels: Good for Contribution
