### ISSUE TITLE
Redirect with trailing slash loses selected language

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#2723] opened 2015-11-04 14:10 UTC
I just noticed, that the redirects on URLs with trailing slashes do not respect the currently selected language of a user. I tested this on CKAN 2.4.1.

E.g.
* I visit http://demo.ckan.org/de/dataset/data-test1/
* I expect to be redirected to http://demo.ckan.org/de/dataset/data-test1
* Instead I end up on http://demo.ckan.org/dataset/data-test1 (thus loosing the selected language)

**Comment by amercader** [comment] 2015-11-05 14:56
This is caused by a combination of

1. The [i18n middleware](https://github.com/ckan/ckan/blob/master/ckan/config/middleware.py#L191:L228) stripping the language bit on all requests and *modifying the original URL sent*

2. This catch-all [route](https://github.com/ckan/ckan/blob/master/ckan/config/routing.py#L425:L426) to redirect URLs with trailing slashes.


I can't think of an easy fix for this, because when the lang bit is stripped in the i18n middleware we don't know if the URL will be redirected.

**Comment by metaodi** [comment] 2015-11-06 12:59
I see. It's not a big issue, as all the links are correct, it's just of someone edits the URL manually and forgets about the trailing slash. Plus I think it's good practice to redirect to the URL the user expects.

**Comment by amercader** [comment] 2015-11-06 13:51
Great, I think I'll close it now as it's not likely that we'll be able to fix it.
Fell free to reopen if you want.

**Closed by amercader** 2015-11-06 13:51 UTC
