### ISSUE TITLE
Activity Stream records don't created for private datasets

### ISSUE THREAD

**Issue by smotornyuk** [ckan/ckan#3160] opened 2016-07-11 17:13 UTC
### Please describe the expected behaviour
Activity Stream should contain records about all changes of dataset from the creation.

### Please describe the actual behaviour
Currently no records added to activity stream if dataset is private. It often not obvious  and even strange(datasets that were private initially have 'User updated ...' as the first record, instead of 'Dataset was created...')

Probably, [this](https://github.com/ckan/ckan/blob/master/ckan/lib/activity_streams_session_extension.py#L87-L88) place should be changed

**Comment by wardi** [comment] 2016-07-12 12:35
This is by design because we don't have a filter on activities to hide them based on your permissions. You would agree that changes to private datasets shouldn't be visible to people that can't see the datasets, right?

Before we can look at adding such a thing we'll need some of the activity performance fixes that @TkTech has been working on, then we need to add a permissions filter. Closing for now.

**Closed by wardi** 2016-07-12 12:35 UTC
