### ISSUE TITLE
template_legacy resources is missing after an installation - /ckan-admin/trash page is unable

### ISSUE THREAD

**Issue by Jan-Marcek** [ckan/ckan#2283] opened 2015-02-13 14:27 UTC
I'm unable to purge deleted dataset via trash webpage.

I'm using https://github.com/ckan/ckan/tree/ckan-2.2.1

```
[Fri Feb 13 16:14:48 2015] [error] 2015-02-13 16:14:48,485 INFO  [ckan.lib.base]  /api/i18n/en render time 0.001 seconds
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] Error - <class 'genshi.template.loader.TemplateNotFound'>: Template "layout.html" not found
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] URL: http://XXXX/ckan-admin/trash
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/weberror/errormiddleware.py', line 162 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   app_iter = self.application(environ, sr_checker)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   resp = self.call_func(req, *args, **self.kwargs)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   return self.func(req, *args, **kwargs)

[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   application, catch_exc_info=False)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   app_iter = application(self.environ, start_response)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   resp = self.call_func(req, *args, **self.kwargs)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   return self.func(req, *args, **kwargs)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   response = request.get_response(self.app)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   application, catch_exc_info=False)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   app_iter = application(self.environ, start_response)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   return self.app(environ, start_response)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   return self.wrap_app(environ, session_start_response)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   response = self.app(environ, start_response)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   response = self.dispatch(controller, environ, start_response)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   return controller(environ, start_response)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/lib/base.py', line 346 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   res = WSGIController.__call__(self, environ, start_response)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   response = self._dispatch_call()
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   response = self._inspect_call(func)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   result = self._perform_call(func, args)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   return func(**args)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/controllers/admin.py', line 105 in trash
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   return base.render('admin/trash.html')
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/lib/base.py', line 224 in render
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   loader_class=loader_class)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   return render_func()
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/lib/base.py', line 176 in render_template
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   strip_whitespace=True))
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/genshi/core.py', line 183 in render
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   return encode(generator, method=method, encoding=encoding, out=out)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/genshi/output.py', line 57 in encode
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   return _encode(''.join(list(iterator)))
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/genshi/output.py', line 339 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   for kind, data, pos in stream:
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/genshi/output.py', line 670 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   for kind, data, pos in stream:
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/genshi/output.py', line 771 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   for kind, data, pos in chain(stream, [(None, None, None)]):
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/genshi/output.py', line 586 in __call__
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   for ev in stream:
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/genshi/core.py', line 288 in _ensure
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   for event in stream:
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/genshi/template/base.py', line 618 in _include
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   for event in tmpl.generate(ctxt, **vars):
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/genshi/template/base.py', line 617 in _include
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   cls=cls or self.__class__)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/genshi/template/loader.py', line 246 in load
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1]   raise TemplateNotFound(filename, search_path)
[Fri Feb 13 16:15:03 2015] [error] [client 127.0.0.1] TemplateNotFound: Template "layout.html" not found

```

**Comment by george-sattler** [comment] 2015-02-16 00:26
HI @Jan-Marcek . I just tried this but I couldn't reproduce the error on 2.2.1. 
The error would definitely occur if the layout.html template was missing from your CKAN source directory for some reason. Is this file definitely present? 
```
ckan/ckan/templates_legacy/layout.html
```

**Comment by Jan-Marcek** [comment] 2015-02-16 08:48
Thank you very much for your answer.

Maybe It is about how I'm installing ckan.
I use python setup.py install (on M$ machine)

I'm unable to find layout.html in installed ckan but I can see in source directory.
I think that layout.html is not "packed" as resource.

**Comment by Jan-Marcek** [comment] 2015-02-16 09:06
Ok, I have found what is wrong: 
You has to add a line into MANIFEST.in 
```
recursive-include ckan/templates_legacy *
```

**Comment by Jan-Marcek** [comment] 2015-02-16 12:32
please have a look at https://github.com/ckan/ckan/pull/2288  - this fixed my problem.

**Comment by amercader** [comment] 2016-12-06 11:04
This is now fixed on modern CKANs

**Closed by amercader** 2016-12-06 11:04 UTC
