### ISSUE TITLE
can't preview muti sheets .xls or .xlsx file online 

### ISSUE THREAD

**Issue by johnxue2013** [ckan/ckan#2720] opened 2015-11-03 06:45 UTC
this problem happens a month agao(sorry, i was a little busy), i have installed datastore and datapush correctly, when i upload the .xls file or .xlsx file that contain more than one sheet, i cant preivew it，but if uploaded was only one sheet,no matter .xls or .xlsx，preivew works fine, i read the code, found when upload only one sheet file, the data of the sheet contain will be insert to posgren database。when preview this file,ckan
will select these data and show it。if multi，ckan won't do that。i don't understand is this normal？

**Comment by rossjones** [comment] 2015-11-03 12:42
Only one sheet is converted in the datapusher and this is a duplicate of https://github.com/ckan/datapusher/issues/71 - which is also discussed at https://github.com/ckan/ideas-and-roadmap/issues/124. Unfortunately this isn't a small amount of work, and so unlikely to be fixed/implemented very soon.

The other issue is that the preview won't handle multiple sheets even if it is provided them (somehow).

As a short-term workaround you could use https://github.com/jqnatividad/ckanext-officedocs which allows you to view all of the sheets on an XLS/XLSX up to about 5Mb in size.

It might be best to keep track of the two issues mentioned above to see where there is progress on this. Will close this as a duplicate in the meantime.

**Closed by rossjones** 2015-11-03 12:42 UTC
