### ISSUE TITLE
resource_create crashes on missing format 

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2665] opened 2015-10-01 05:56 UTC
For resource_create, format is described in the documentation as optional, however the following call will generate a 500 error (key error)

```
curl -X POST "http://demo.ckan.org:80/api/3/action/resource_create" \
-d '{ "name": "room1_room", "url": "test", "package_id": "0420f984-d5a9-4681-bc6f-acfd6888e286" }' \
-H "Authorization: MY-API-KEY"
```

but the following works

```
curl -X POST "http://demo.ckan.org:80/api/3/action/resource_create" \
-d '{ "name": "room1_room", "url": "test", "package_id": "0420f984-d5a9-4681-bc6f-acfd6888e286", "format": "csv" }' \
-H "Authorization: MY-API-KEY"
```

**Comment by amercader** [comment] 2015-10-01 08:50
I'm almost certain that thid is due to a view plugin assuming that format is there when checking if it can be rendered (ie `res['format']` rather than `res.get('format')`. Provably geoview. I'll have a look as soon as I get the chance.

**Comment by amercader** [comment] 2015-10-06 12:41
:thumbsup:

**Comment by mattfullerton** [comment] 2015-10-06 12:59
I can "confirm" that the request doesn't generate an error when no default views are enabled, on a CKAN close to master.

**Comment by amercader** [comment] 2015-10-15 10:08
I can confirm that this was due to an outdated version of ckanext-geoview and that is now fixed on demo.ckan.org

**Closed by amercader** 2015-10-15 10:08 UTC
