### ISSUE TITLE
KeyError: 'resources'

### ISSUE THREAD

**Issue by yanikkoval** [ckan/ckan#2816] opened 2015-12-29 16:21 UTC
I'm implement simple dataset extra field: https://ckan.readthedocs.org/en/latest/extensions/adding-custom-fields.html

Followed all documentation and code is simple. But when i submit my dataset (after adding resrce) got next error: 
```
File '/usr/lib/ckan/default/src/ckan/ckan/controllers/package.py', line 712 in new_resource
  get_action('resource_create')(context, data)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 429 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py', line 308 in resource_create
  errors = e.error_dict['resources'][-1]
KeyError: 'resources'
```

Can you point me? Why this is happening, I never touch resource part. 
Maybe because I have many plugins activated in my class? Like:

```
    p.implements(p.IConfigurer)
    p.implements(p.ITemplateHelpers)
    p.implements(p.IDomainObjectModification, inherit=True)
    p.implements(p.IDatasetForm)

```
THX!

**Comment by wide-awake** [comment] 2015-12-29 17:42
Think thought may be useful:
http://redmine.dguteam.org.uk/issues/1281#note-2 

I'm using custom schema (as tutorial says), but resource need default schema? 
I don't touch resources, extra field for package only.

**Comment by wardi** [comment] 2015-12-31 18:10
This exception happens when there is a validation error in the package while updating the resource. The resource action assumes the error was from the resource, then fails trying to get the error message.

We should really fix this one. Thank you for the reminder.

**Comment by wide-awake** [comment] 2016-01-04 09:29
@wardi any thoughts how can dodge that error? It keeps throwing 504 error

**Comment by wardi** [comment] 2016-01-04 18:18
@wide-awake the error is coming from one of the dataset fields in your custom schema. Validation is done on the dataset and its resources when adding a resource and the resource code doesn't expect the fields in the dataset to fail validation when they have already passed once.

If you set a breakpoint and look at the value of error_dict you'll probably be able to figure out what's wrong.

**Comment by nabiltntn** [comment] 2016-07-13 08:39
I have the same issue and the real validation error is about the the dataset and not the resource.

Loging the exception in create.py : `resource_create` shows a `{'id': [u'Dataset id already exists']}` while applying the `package_id_does_not_exist` validator for the  `default_create_package_schema` schema in `schema.py`

**Comment by TkTech** [comment] 2016-10-07 10:50
Closing as a duplicate of #2331 (which has an associated PR)

**Closed by TkTech** 2016-10-07 10:50 UTC
